### ISSUE TITLE
Folder sync not stopped when dat moved to trash

### ISSUE THREAD

**Issue by paul90** [beakerbrowser/beaker#1003]
Operation System: macOS 10.13.4
Beaker version: 738a5ebfc7b4a92d66a82e421c077c8731180d89

Folder sync continues to happen after dat is moved to trash in library

```
changed detected /lib/sitemapHandler.coffee
already syncing, ignored
syncing to archive [ { change: 'del', type: 'file', path: '/lib/sitemap.coffee' },
  { change: 'add',
    type: 'file',
    path: '/lib/sitemapHandler.coffee' } ]
syncing to folder []
```
if the folder is then deleted from trash, the folder sync still continues but fails with:
```
changed detected /lib/sitemapHandler.coffee
ok timed out
Unhandled Rejection at: Promise Promise {
  <rejected> { ArchiveNotWritableError: Cannot write to this archive ; Not the owner
    at syncFolderToArchive (/Users/Paul/Projects/dat/beaker/app/background-process.build.js:3043:32)
    at Timeout.archive.syncFolderToArchiveTimeout.setTimeout [as _onTimeout] (/Users/Paul/Projects/dat/beaker/app/background-process.build.js:3084:17)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5) name: 'ArchiveNotWritableError', archiveNotWritable: true } } reason: { ArchiveNotWritableError: Cannot write to this archive ; Not the owner
    at syncFolderToArchive (/Users/Paul/Projects/dat/beaker/app/background-process.build.js:3043:32)
    at Timeout.archive.syncFolderToArchiveTimeout.setTimeout [as _onTimeout] (/Users/Paul/Projects/dat/beaker/app/background-process.build.js:3084:17)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5) name: 'ArchiveNotWritableError', archiveNotWritable: true }
```

I would expect the sync process to stop for any particular dat when it is deleted.

**Comment by pfrazee** [comment]
Whoops, good catch. Thanks for reporting
