### ISSUE TITLE
Beaker fails to start on Debian

### ISSUE THREAD

**Issue by theorangepotato** [beakerbrowser/beaker#1055]
**Operation System:** Debian Stretch
**Beaker version:** Beaker 0.8.0-prerelease.6 (commit: cee7b37078e00cb6604aba5ee24e3184c922483a, current HEAD)

I haven't opened Beaker in a few months, and so I ran `git pull` and `npm run burnthemall`, but upon running `npm start`, I received the following error message:

```
> beakerbrowser@ start $Path_to_Beaker
> gulp start

[19:00:15] Using gulpfile $Path_to_Beaker/gulpfile.js
[19:00:15] Starting 'start'...
Spawning electron $Path_to_Beaker/node_modules/electron/dist/electron
[19:00:15] Finished 'start' after 3.64 ms
Logfile: $Path_to_Home/.config/Beaker Browser/debug.log
App threw an error during load
TypeError: debug.overrideUseColors is not a function
    at setup$1 ($Path_to_Beaker/app/background-process.build.js:57:9)
    at $Path_to_Beaker/app/background-process.build.js:3158:1
    at Object.<anonymous> ($Path_to_Beaker/app/background-process.build.js:3247:2)
    at Object.<anonymous> ($Path_to_Beaker/app/background-process.build.js:3248:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at loadApplicationPackage ($Path_to_Beaker/node_modules/electron/dist/resources/default_app.asar/main.js:287:12)
    at Object.<anonymous> ($Path_to_Beaker/node_modules/electron/dist/resources/default_app.asar/main.js:328:5)
    at Object.<anonymous> ($Path_to_Beaker/node_modules/electron/dist/resources/default_app.asar/main.js:365:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Object.<anonymous> ($Path_to_Beaker/node_modules/electron/dist/resources/electron.asar/browser/init.js:186:8)
    at Object.<anonymous> ($Path_to_Beaker/node_modules/electron/dist/resources/electron.asar/browser/init.js:188:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Function.Module.runMain (module.js:683:10)
    at startup (bootstrap_node.js:196:16)
    at bootstrap_node.js:622:3
```

and it would hang in an apparent infinite loop. I assumed this may have been due to some antiquity with my files that `burnthemall` wasn't properly dealing with, so I deleted the entire repository, cloned it again, and rebuilt it from scratch; however, this error remains. Moving the `.config/Beaker Browser/` folder also did not solve the issue.

**Comment by pfrazee** [comment]
This looks like an npm blug. What version of node & npm are you using to build?

We import a custom build of https://npm.im/debug that's located at https://github.com/beakerbrowser/debug/tree/configurable. We use this line in our package.json to do it:

```
"debug": "git://github.com/beakerbrowser/debug.git#8d79a96e2c5f79527d7580960be3da9ae246ed8e"
```

I'd also be interested what you have at `./app/node_modules/debug/package.json`.

**Comment by theorangepotato** [comment]
**npm version:** 3.10.10
**node version:** v6.14.3

I believe I am up-to-date with those packages in Debian Stretch. However, my [`package.json`](https://github.com/beakerbrowser/beaker/files/2139774/package.json.txt) is weird. It seems to have the following line instead:
```
"raw": "debug@git://github.com/beakerbrowser/debug.git#8d79a96e2c5f79527d7580960be3da9ae246ed8e"
```

**Comment by pfrazee** [comment]
That actually looks right. It's our custom version of `debug`.

This might have been a mistake dealing with `@beaker/core`, which didn't include the right `debug` in its package.json.

Try pulling master and burning them all again.

**Comment by royhodge** [comment]
have you checked this? --> sudo mount -o remount,exec /tmp
^^^ fixes browser bug i was having last night --> https://github.com/brave/browser-laptop/issues/900

**Comment by theorangepotato** [comment]
Okay, so I realized that the Debian packages were several releases behind main, so I updated them from the official repositories. Now:

**npm version:** 6.1.0
**node version:** 10.5.0

I have also pulled up to the current head (decaf0221e3873f8fe47c1e7b1649021302c05af), and tried `npm install`, but I now get this output when running the command:

```
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm ERR! Unexpected end of JSON input while parsing near '...3Y56rXcuMJ+nU2aPKF8Fc'

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2018-07-05T17_05_26_855Z-debug.log
```

The referenced log file is [here](https://github.com/beakerbrowser/beaker/files/2167553/2018-07-05T17_05_26_855Z-debug.log). It seems to be a problem with the `ajv@^5.1.0`? I have tried this several times over the course of several days and have repeatedly gotten this error, even on clean clones and clean node installs.

@royhodge Thanks for the tip! The Brave issue looks like it was a problem with a binary not being executable due to the default mount permissions in the `/tmp` directory, whereas I believe this issue is a package parsing and dependency issue.

**Comment by LWFlouisa** [comment]
I wonder if this is related to why my beaker wont start in Trisquel? I know they had a Debian version at some point right?
