### ISSUE TITLE
Issues getting started on Trisquel 7

### ISSUE THREAD

**Issue by LWFlouisa** [beakerbrowser/beaker#1088]
Operation System: Trisquel 7
Beaker version: Most recent version

Is anyone else having trouble getting beaker-browser to boot in Trisquel 7? I can get it to work just fine in Linux Mint 18.1.

If Trisquel 7 were free, not allowing one to run beaker doesn't seem very freedom respecting.

**Comment by paul90** [comment]
Just tried a quick install of Trisquel 7 on a virtual machine... running the Beaker AppImage from the command line gives the following error:
```
./beaker-browser-0.8.0-prerelease.6-x86_64.AppImage 
installed: X-AppImage-BuildId=b2b7c780-638c-11a8-33e3-a1d86c51a213 image: X-AppImage-BuildId=b2b7c780-638c-11a8-33e3-a1d86c51a213
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/.org.chromium.Chromium.TThDV9)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:186:18)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/tmp/.mount_beaker3HPKtq/app/resources/app.asar/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Object.<anonymous> (/tmp/.mount_beaker3HPKtq/app/resources/app.asar/node_modules/sqlite3/lib/sqlite3.js:190:3)
```
Trisquel 7 is based on Ubuntu 14.04 LTS, so building the AppImage on that should solve the issue.

**Comment by pfrazee** [comment]
Oh yeah we got that issue in another distro, I think there’s an issue for it. You’ll probably have to build from source for now

**Comment by LWFlouisa** [comment]
I was just curious if other encountered it. Thanks for the help.
