### ISSUE TITLE
Can't load videos on-demand

### ISSUE THREAD

**Issue by dcposch** [beakerbrowser/beaker#1140]
Operation System: macOS High Sierra
Beaker version: v0.8.0-prelease-9

### works in chrome

https://dcpos.ch/beaker-test/06-bazooka-city.mp4

video should start playing near instantly

### broken in beaker

go to dat://dcpos.ch/beaker-test/06-bazooka-city.mp4

the video opens. once you click play, you get a frozen gray screen. the console shows the following error:

![screen shot 2018-09-09 at 12 59 02 am](https://user-images.githubusercontent.com/169280/45262776-727b7e00-b3d2-11e8-9111-0bad13ed025c.png)

looks like the internal beaker HTTP-to-Dat bridge is returning a 500 error.

**note that when i came back much later, once the whole dat was downloaded, the video worked.** Beaker can render the mp4 just fine, but there's a problem downloading files incrementally over dat.

## investigation

to confirm the video files were valid and part of the dat archive, i ran the following:

```
dat clone dat://36abda5bff5a816b4e69f45e41c6778ebb3c34e45bc6a5e5758e2f047559884b
```

the dat download creates the video files quickly. **however, the files are not playable (zeros/corrupt data) until they finish downloading.**

this may be related to the issue i saw in Beaker.

**Comment by dcposch** [comment]
@pfrazee is there an easy way to see the main/renderer process logs?

i bet the 500 corresponds to a stacktrace in a different process, and i'd paste it here if i knew where to find it

**Comment by pfrazee** [comment]
There's a debug log you can check
![screen shot 2018-09-11 at 11 27 12 am](https://user-images.githubusercontent.com/1270099/45373719-b9759900-b5b5-11e8-97d9-b41124df5419.png)

**Comment by pfrazee** [comment]
Okay I had to deploy a new internal data format to check into this, because without sparse-file support (which my MacOS version lacks) Beaker would allocate 11GB upon visit 🤣. Okay FIXED THAT, and now I could check my log and see what happens. Here it is:

```
Error reading file Error: Download was cancelled
    at Feed.undownload (/Users/paulfrazee/my/beaker-core/node_modules/hypercore/index.js:353:30)
    at onend (/Users/paulfrazee/my/beaker-core/node_modules/hyperdrive/index.js:498:24)
    at done (/Users/paulfrazee/my/beaker-core/node_modules/hypercore/index.js:586:5)
    at /Users/paulfrazee/my/beaker-core/node_modules/hypercore/index.js:554:40
    at onroot (/Users/paulfrazee/my/beaker-core/node_modules/hypercore/index.js:600:30)
    at onleftchild (/Users/paulfrazee/my/beaker-core/node_modules/hypercore/index.js:616:7)
    at Request._callback (/Users/paulfrazee/my/beaker-core/node_modules/hypercore/lib/storage.js:166:5)
    at Request.callback (/Users/paulfrazee/my/beaker-core/node_modules/random-access-storage/index.js:161:8)
    at onread (/Users/paulfrazee/my/beaker-core/node_modules/random-access-file/index.js:80:31)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:658:17)
```

I'll need to check with maf to find out why this might be happening.

**Comment by pfrazee** [comment]
Video playback is fixed in the upcoming release
