### ISSUE TITLE
dat-serve Failed to load sodium-native

### ISSUE THREAD

**Issue by nkhine** [beakerbrowser/beaker#1269]
Operation System:

```
khine@araweelo   ~/go/src/github.com/beakerbrowser/beaker     master   uname -a                                                                                                ✔  5057  14:39:49 
Linux araweelo 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

Beaker version:
cloned from master https://github.com/beakerbrowser/beaker/commit/610418bf1b0f03ea010e9c7eb3c80c0cac132a2f

```
khine@araweelo   ~/go/src/github.com/beakerbrowser/beaker     master   npm start                                                                                               ✔  5053  14:10:24 

> beakerbrowser@ start /home/khine/go/src/github.com/beakerbrowser/beaker
> gulp start

[14:10:29] Using gulpfile ~/go/src/github.com/beakerbrowser/beaker/gulpfile.js
[14:10:29] Starting 'start'...
[14:10:29] Starting '<anonymous>'...
Spawning electron /home/khine/go/src/github.com/beakerbrowser/beaker/node_modules/electron/dist/electron
dat-serve Failed to load sodium-native. Performance may be degraded. Error: No native build was found for runtime=electron abi=64 platform=linux arch=x64

Failed to load sodium-native. Performance may be degraded. Error: No native build was found for runtime=electron abi=64 platform=linux arch=x64
    at Function.load.path (/home/khine/go/src/github.com/beakerbrowser/beaker/app/node_modules/node-gyp-build/index.js:36:9)
    at load (/home/khine/go/src/github.com/beakerbrowser/beaker/app/node_modules/node-gyp-build/index.js:13:23)
    at Object.<anonymous> (/home/khine/go/src/github.com/beakerbrowser/beaker/app/node_modules/sodium-native/index.js:1:194)
    at Object.<anonymous> (/home/khine/go/src/github.com/beakerbrowser/beaker/app/node_modules/sodium-native/index.js:5:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
[ dat-daemon ] Starting...
[ dat-daemon ] Loading: /home/khine/go/src/github.com/beakerbrowser/beaker/app/dat-daemon.js
Logfile: /home/khine/.config/Beaker Browser/debug.log
[ dat-daemon ] Uncaught (in promise) undefined
[ dat-daemon ] Uncaught (in promise) undefined
Detected Linux. Setting up spell check for Linux.
(electron) The 'lstatSyncNoException' function has been deprecated and marked for removal.

```

**Comment by pfrazee** [comment]
Hi @nkhine. Did you try running `npm run rebuild` ?

**Comment by nkhine** [comment]
yes, i followed the install instructions and run the `npm run rebuild`

**Comment by pfrazee** [comment]
Hmm okay. Which version of Ubuntu is that?

(FWIW this will affect performance but wont stop Beaker from working.)

**Comment by nkhine** [comment]
```
 khine@araweelo   ~/go/src/github.com/beakerbrowser/beaker     master   lsb_release -a                                                                                          ✔  5198  20:06:40 
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
```

beaker does run

**Comment by pfrazee** [comment]
Hmm! Are there any errors during the `npm run rebuild` ?
