### ISSUE TITLE
Beaker won't run

### ISSUE THREAD

**Issue by JHM-O** [beakerbrowser/beaker#1277]
Operation System: Debian testing
Beaker version: latest git-clone

Was trying to install Beaker browser conform instructions on Beaker install page. Wouldn't work. Got error message as listed below.
So, what to do about this?

beaker$ npm start

> beakerbrowser@ start /extra_fs/beaker
> gulp start

[15:51:16] Using gulpfile /extra_fs/beaker/gulpfile.js
[15:51:16] Starting 'start'...
[15:51:16] Starting '<anonymous>'...
Spawning electron /extra_fs/beaker/node_modules/electron/dist/electron
App threw an error during load
Error: Cannot find module '/extra_fs/beaker/app/node_modules/sqlite3/lib/binding/electron-v3.0-linux-x64/node_sqlite3.node'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._resolveFilename (/extra_fs/beaker/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/extra_fs/beaker/app/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Object.<anonymous> (/extra_fs/beaker/app/node_modules/sqlite3/lib/sqlite3.js:190:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module '/extra_fs/beaker/app/node_modules/sqlite3/lib/binding/electron-v3.0-linux-x64/node_sqlite3.node'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._resolveFilename (/extra_fs/beaker/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/extra_fs/beaker/app/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Object.<anonymous> (/extra_fs/beaker/app/node_modules/sqlite3/lib/sqlite3.js:190:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)

**Comment by pfrazee** [comment]
Huh, that's strange. Have you tried running `npm run rebuild` or `npm run burnthemall` ?

**Comment by JHM-O** [comment]
I add some logs to give more insight in the problem.

[Beaker - burnthemall-log.docx](https://github.com/beakerbrowser/beaker/files/2660627/Beaker.-.burnthemall-log.docx
[Beaker - rebuild-log.docx](https://github.com/beakerbrowser/beaker/files/2660630/Beaker.-.rebuild-log.docx)

Anybody got a clue?

**Comment by pfrazee** [comment]
Might relate to outdated software. You're `node-gyp` instance is outdated. You could also update node to 10.x.

Basically `node-gyp` is choking on a bad reference while it's building the sqlite `.node` file, which makes me think the software needs to be updated.

It's using node-gyp at `/usr/share/node-gyp` which suggests to me that's a global install, so you might need to update it by running `npm i -g node-gyp`. I'd start by updating node, and if `burnthemall` still fails then try updating [node-gyp])(https://github.com/nodejs/node-gyp) to latest.

**Comment by alexandre1985** [comment]
You can install the [Beaker's Linux AppImage file](https://beakerbrowser.com/install/), *make it executable* using `chmod +x` and double click on it.
I believe it will work... it did for me.

**Comment by JHM-O** [comment]
That's correct. Already tried this, and it works for me too. But this is the easy way.
I like to experiment, so I also wanted to see how things went the hard way.
I followed pfrazee's advise, and now I've got it working also when building from source.
So, time to explore this Beakerthing a bit further.

**Comment by alexandre1985** [comment]
Ok.
One thing: I believe that '.AppImage's update automatically. So it is one plus for it.
With Beaker source code you have to update the source code manually and recompiling it into an app. So, not so easy.
Tell me if I'm wrong (if Beaker source code compiled app can update itself without recompiling the source code)

**Comment by JHM-O** [comment]
O, I don't mind that.

I don't really know whether compiling from source results in an AppImage or just a Beaker-binary. After compiling you run npm start and get the Beaker startpage. I can't find any reference to the AppImage in the Beaker-directories.
Compiling and updating from source is just somewhat more instructive, and that's important to me.
And then again, I don't even know whether I will be trying Beaker for very long. There's still not very much peer to peer webcontent available, is there? And Beaker is still beta, so day to day internetting with it will probably be quite error-prone.
We'll see..

**Comment by alexandre1985** [comment]
I know its still beta. For me it only crashed on time, but a when reopening Beaker everything was fine.
There isn't much dat:// content I guess but it also supports http/s which is great.
I quite like the browser so far :+1:  :smiley:

If your issue is resolve you can close this issue.
