### ISSUE TITLE
sodium native installation failure

### ISSUE THREAD

**Issue by hossameldeen** [beakerbrowser/beaker#1336]
Operation System: Ubuntu 16.04
Beaker version: Latest-source

- When I run `burnthemall`, I notice:

<details>
<summary>(1) sodium-native failure to install or something (click to expand)</summary>

```
> sodium-native@2.2.6 install /home/hossameldeen/Development/projects/beaker/app/node_modules/sodium-native
> node-gyp-build "node preinstall.js" "node postinstall.js"

./configure: 2: cd: can't cd to libsodium
You need to run "npm run fetch-libsodium" first
/home/hossameldeen/Development/projects/beaker/app/node_modules/sodium-native/preinstall.js:119
    if (err) throw err
             ^

Error: ./configure exited with 1
    at ChildProcess.<anonymous> (/home/hossameldeen/Development/projects/beaker/app/node_modules/sodium-native/preinstall.js:149:25)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sodium-native@2.2.6 install: `node-gyp-build "node preinstall.js" "node postinstall.js"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sodium-native@2.2.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

</details>

<details>
<summary>(2) warning about some modules not being resolved in `build` (click to expand)</summary>

```
npm run build

> beakerbrowser@ build /home/hossameldeen/Development/projects/beaker
> gulp build

[21:53:49] Using gulpfile ~/Development/projects/beaker/gulpfile.js
[21:53:49] Starting 'build'...
[21:53:49] Starting 'bundle'...
[21:53:49] Starting 'burnthemall-maybe'...
[21:53:49] Starting 'burnthemallMaybeTask'...
[21:53:49] Finished 'burnthemallMaybeTask' after 5.51 ms
[21:53:49] Finished 'burnthemall-maybe' after 7.47 ms
[21:53:49] Starting 'bundleTask'...
'@beaker/core/webview' is imported by app/webview-preload.js, but could not be resolved – treating it as an external dependency
'@beaker/core/lib/strings' is imported by app/builtin-pages/views/library-view.js, but could not be resolved – treating it as an external dependency
'@beaker/core/lib/error-page' is imported by app/shell-window/pages.js, but could not be resolved – treating it as an external dependency
'TimeoutError' is imported from external module 'beaker-error-constants' but never used
'TimeoutError' is imported from external module 'beaker-error-constants' but never used
'TimeoutError' is imported from external module 'beaker-error-constants' but never used
'@beaker/core/lib/const' is imported by app/builtin-pages/com/files-browser/files-flat-view.js, but could not be resolved – treating it as an external dependency
'TimeoutError' is imported from external module 'beaker-error-constants' but never used
'@beaker/core/lib/strings' is imported by app/background-process/ui/permissions.js, but could not be resolved – treating it as an external dependency
'@beaker/core/lib/const' is imported by app/background-process/browser.js, but could not be resolved – treating it as an external dependency
'@beaker/core/lib/const' is imported by app/background-process/analytics.js, but could not be resolved – treating it as an external dependency
'@beaker/core/lib/error-page' is imported by app/background-process/protocols/beaker.js, but could not be resolved – treating it as an external dependency
'default' is imported from external module 'os' but never used
[21:54:05] Finished 'bundleTask' after 16 s
[21:54:05] Finished 'bundle' after 16 s
[21:54:05] Starting 'less'...
[21:54:05] Starting 'burnthemall-maybe'...
[21:54:05] Starting 'burnthemallMaybeTask'...
[21:54:05] Finished 'burnthemallMaybeTask' after 2.14 ms
[21:54:05] Finished 'burnthemall-maybe' after 4.02 ms
[21:54:05] Starting 'lessTask'...
[21:54:05] Finished 'lessTask' after 73 ms
[21:54:05] Finished 'less' after 80 ms
[21:54:05] Finished 'build' after 16 s
```

</details>

- Beaker runs, though.

- Might be related: #1269. Opened another issue because I can't see the `dat-serve failed to sodium-native`.

- **Question:** Given the error logs above, can I safely ignore them & continue using Beaker for now?

**Comment by pfrazee** [comment]
I've been getting this as well. You actually should be able to ignore it; you'll just suffer a performance penalty.

@mafintosh any idea why sodium-native is suddenly asking us to run `fetch-libsodium` when we do rebuilds?

**Comment by mafintosh** [comment]
@pfrazee hmm, no all the source code should be included. @emilbayes did we forget to include in latest build?

**Comment by emilbayes** [comment]
Yeah looks like the source is missing. I will do a new release soon anyway, since libsodium 1.0.17 came out recently

**Comment by pfrazee** [comment]
Thanks @emilbayes

**Comment by emilbayes** [comment]
@pfrazee 2.3.0 is out now with source included :)
