### ISSUE TITLE
Freeze/Crash when clicking Explore Link in new tab window

### ISSUE THREAD

**Issue by lazaruslarue** [beakerbrowser/beaker#1365]
Operation System: Ubuntu
Beaker version: `master` @ `commit 8547805bb8cf102a6c461a8e966aeea4e563ea4 (HEAD -> master, origin/master, origin/HEAD)`

this morning i followed (closely) the instructions to build from source on Ubuntu. 

noticed some warnings during the install beginning with... there are probably 100x warnings such as these: 

```t
make: Entering directory '/home/laz/beaker/app/node_modules/spellchecker/build'
  CXX(target) Release/obj.target/hunspell/vendor/hunspell/src/hunspell/affentry.o
In file included from ../vendor/hunspell/src/hunspell/affentry.cxx:9:0:
../vendor/hunspell/src/hunspell/affentry.hxx:30:105: warning: converting to non-pointer type ‘short unsigned int’ from NULL [-Wconversion-null]
 osfx(const char * word, int len, char in_compound, const FLAG needflag = NULL);
                                                                          ^~~~
../vendor/hunspell/src/hunspell/affentry.hxx:93:114: warning: converting to non-pointer type ‘short unsigned int’ from NULL [-Wconversion-null]
 har * word, int len, int optflags, PfxEntry* ppfx, const FLAG needflag = NULL);
                                                                          ^~~~
../vendor/hunspell/src/hunspell/affentry.cxx: In member function ‘int PfxEntry::test_condition(const char*)’:
../vendor/hunspell/src/hunspell/affentry.cxx:113:20: warning: this statement may fall through [-Wimplicit-fallthrough=]
          case '.': if (!pos) { // dots are not metacharacters in groups: [.]
                    ^~
../vendor/hunspell/src/hunspell/affentry.cxx:120:5: note: here
     default: {
     ^~~~~~~
../vendor/hunspell/src/hunspell/affentry.cxx: In member function ‘int SfxEntry::test_condition(const char*, const char*)’:
../vendor/hunspell/src/hunspell/affentry.cxx:501:19: warning: this statement may fall through [-Wimplicit-fallthrough=]
         case '.': if (!pos) { // dots are not metacharacters in groups: [.]
                   ^~
../vendor/hunspell/src/hunspell/affentry.cxx:516:5: note: here
     default: {
     ^~~~~~~
  CXX(target) Release/obj.target/hunspell/vendor/hunspell/src/hunspell/affixmgr.o
In file included from ../vendor/hunspell/src/hunspell/affixmgr.cxx:12:0:
../vendor/hunspell/src/hunspell/affentry.hxx:30:105: warning: converting to non-pointer type ‘short unsigned int’ from NULL [-Wconversion-null]
 osfx(const char * word, int len, char in_compound, const FLAG needflag = NULL);
```

i'm able to visit dat://datproject.org/ and it looks wonderful :) this is an exciting project!

when i type this link into the browser, i get a DNS error @ dat://explore.beakerbrowser.com

```
Page Not Found
No DNS record found for dat://explore.beakerbrowser.com
```

however if i click the purple link from the new-tab "Explore p2p sites..." everything craps out and i have to break out of `npm start`. 

```
laz {~/beaker}±(master); greetings, earthling [102.084Mb]$ ☞ npm start

> beakerbrowser@ start /home/laz/beaker
> gulp start

[07:41:25] Using gulpfile ~/beaker/gulpfile.js
[07:41:25] Starting 'start'...
[07:41:25] Starting '<anonymous>'...
Spawning electron /home/laz/beaker/node_modules/electron/dist/electron
Starting external process dat-daemon
dat-daemon ready
Logfile: /home/laz/.config/Beaker Browser/debug.log
Detected Linux. Using default en_US spell check dictionary.
Failed to load pins SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at loadPins (/home/laz/beaker/app/background-process.build.js:3033:14)
configureFolderToArchiveWatcher() false false
Unhandled Rejection at: Promise Promise {
  <rejected> { InvalidDomainName: Invalid domain name
      at resolveName.apply.catch._ (/home/laz/beaker/app/node_modules/@beaker/core/dat/dns.js:16:13) name: 'InvalidDomainName', invalidDomainName: true } } reason: { InvalidDomainName: Invalid domain name
    at resolveName.apply.catch._ (/home/laz/beaker/app/node_modules/@beaker/core/dat/dns.js:16:13) name: 'InvalidDomainName', invalidDomainName: true }
Unhandled Rejection at: Promise Promise {
  <rejected> { InvalidDomainName: Invalid domain name
      at resolveName.apply.catch._ (/home/laz/beaker/app/node_modules/@beaker/core/dat/dns.js:16:13) name: 'InvalidDomainName', invalidDomainName: true } } reason: { InvalidDomainName: Invalid domain name
    at resolveName.apply.catch._ (/home/laz/beaker/app/node_modules/@beaker/core/dat/dns.js:16:13) name: 'InvalidDomainName', invalidDomainName: true }
^C
laz {~/beaker}±(master); greetings, earthling [102.084Mb]$ ☞ npm start

> beakerbrowser@ start /home/laz/beaker
> gulp start

[07:43:35] Using gulpfile ~/beaker/gulpfile.js
[07:43:35] Starting 'start'...
[07:43:35] Starting '<anonymous>'...
Spawning electron /home/laz/beaker/node_modules/electron/dist/electron
Starting external process dat-daemon
dat-daemon ready
Logfile: /home/laz/.config/Beaker Browser/debug.log
Detected Linux. Using default en_US spell check dictionary.
Gtk-Message: 07:43:36.961: GtkDialog mapped without a transient parent. This is discouraged.
Failed to load pins SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at loadPins (/home/laz/beaker/app/background-process.build.js:3033:14)
configureFolderToArchiveWatcher() false false
configureFolderToArchiveWatcher() false false
(node:13085) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 did-navigate listeners added. Use emitter.setMaxListeners() to increase limit
Unhandled Rejection at: Promise Promise {
  <rejected> { InvalidDomainName: Invalid domain name
      at resolveName.apply.catch._ (/home/laz/beaker/app/node_modules/@beaker/core/dahttps://github.com/beakerbrowser/beaker/releasest/dns.js:16:13) name: 'InvalidDomainName', invalidDomainName: true } } reason: { InvalidDomainName: Invalid domain name
    at resolveName.apply.catch._ (/home/laz/beaker/app/node_modules/@beaker/core/dat/dns.js:16:13) name: 'InvalidDomainName', invalidDomainName: true }
Unhandled Rejection at: Promise Promise {
  <rejected> { InvalidDomainName: Invalid domain name
      at resolveName.apply.catch._ (/home/laz/beaker/app/node_modules/@beaker/core/dat/dns.js:16:13) name: 'InvalidDomainName', invalidDomainName: true } } reason: { InvalidDomainName: Invalid domain name
    at resolveName.apply.catch._ (/home/laz/beaker/app/node_modules/@beaker/core/dat/dns.js:16:13) name: 'InvalidDomainName', invalidDomainName: true }
Unhandled Rejection at: Promise Promise {
  <rejected> { InvalidDomainName: Invalid domain name
      at resolveName.apply.catch._ (/home/laz/beaker/app/node_modules/@beaker/core/dat/dns.js:16:13) name: 'InvalidDomainName', invalidDomainName: true } } reason: { InvalidDomainName: Invalid domain name
    at resolveName.apply.catch._ (/home/laz/beaker/app/node_modules/@beaker/core/dat/dns.js:16:13) name: 'InvalidDomainName', invalidDomainName: true }
```

**Comment by pfrazee** [comment]
This is a known issue, unfortunately. See https://github.com/beakerbrowser/beaker/issues/1333. We're waiting on a fix to be merged and released in Electron (https://github.com/electron/electron/pull/17267).

Closing as a duplicate. Sorry you're dealing with this 👎
