### ISSUE TITLE
npm start failed after "burnthemall" with latest "blue" branch

### ISSUE THREAD

**Issue by pmario** [beakerbrowser/beaker#1369]
Operation System: ubuntu 18.04 LTS
Beaker version: latest "blue" branch

I did a "npm run burnthemall"
npm start and got this info.

```
> gulp start

[21:35:41] Using gulpfile ~/git/beaker/gulpfile.js
[21:35:41] Starting 'start'...
[21:35:41] Starting '<anonymous>'...
Spawning electron /home/mario/git/beaker/node_modules/electron/dist/electron
Starting external process dat-daemon
dat-daemon ready
info:     Program start
Logfile: /home/mario/.config/Beaker Browser/debug.log
info:     Initialized dat library {"category":"dat","subcategory":"library"}
info:     [PROFILES] Database at version 23; Running 1 migrations {"category":"sqlite"}
error:    Error while loading watchlist {"category":"dat","subcategory":"watchlist","err":{"errno":1,"code":"SQLITE_ERROR"}}
Unhandled Rejection at: Promise Promise {
  <rejected> Error: Failed to load the watchlist
      at Object.setup (/home/mario/git/beaker/app/node_modules/@beaker/core/dat/watchlist.js:26:11) } reason: Error: Failed to load the watchlist
    at Object.setup (/home/mario/git/beaker/app/node_modules/@beaker/core/dat/watchlist.js:26:11)
info:     Setting bandwidth throttle {"details":{"up":0,"down":0},"category":"dat","subcategory":"daemon"}
```

**Comment by pfrazee** [comment]
@pmario I'm sorry, the blue branch isn't ready for people to use. I make frequent database schema changes which are destructive, and will cause that exact problem to occur.

**Comment by pfrazee** [comment]
It's a little tricky to fix this issue. You basically need to manually open the db using the `sqlite` CLI tool and delete the schemas which the blue branch adds.

**Comment by pmario** [comment]
ok
