### ISSUE TITLE
Settings page blank on macOS 10.15

### ISSUE THREAD

**Issue by da2x** [beakerbrowser/beaker#1417]
Operation System: macOS 10.15 (Beta) 19A471t

Beaker version: 0.8.8

1. Open Settings
2. Try to close the Settings tab

The Settings page is blank. It’s impossible to close the tab without closing the window. Restarting the browser with session restore restores the impossible-to-close-tab.

`beaker://dat-dns-cache/` is also affected. Other internal pages work fine.

Console error:

> objc[2485]: couldn't dlopen libobjc-trampolines.dylib: dlopen(/usr/lib/libobjc-trampolines.dylib, 262): no suitable image found.  Did find:
	/usr/lib/libobjc-trampolines.dylib: file system sandbox blocked stat()

**Comment by pfrazee** [comment]
Hmm yikes. I'll look into it, thanks

**Comment by the-kenny** [comment]
I have the same issue. Note that I also get a node stacktrace just before the described error is printed

```
Error: Request failed: 500
    at /Applications/Beaker Browser.app/Contents/Resources/app.asar/node_modules/nat-upnp/lib/nat-upnp/device.js:151:27
    at Parser.<anonymous> (/Applications/Beaker Browser.app/Contents/Resources/app.asar/node_modules/xml2js/lib/xml2js.js:199:18)
    at Parser.emit (events.js:182:13)
    at SAXParser.saxParser.onclosetag (/Applications/Beaker Browser.app/Contents/Resources/app.asar/node_modules/xml2js/lib/xml2js.js:183:24)
    at emit (/Applications/Beaker Browser.app/Contents/Resources/app.asar/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/Applications/Beaker Browser.app/Contents/Resources/app.asar/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/Applications/Beaker Browser.app/Contents/Resources/app.asar/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/Applications/Beaker Browser.app/Contents/Resources/app.asar/node_modules/sax/lib/sax.js:1436:13)
    at Parser.exports.Parser.Parser.parseString (/Applications/Beaker Browser.app/Contents/Resources/app.asar/node_modules/xml2js/lib/xml2js.js:211:31)
    at Parser.parseString (/Applications/Beaker Browser.app/Contents/Resources/app.asar/node_modules/xml2js/lib/xml2js.js:6:61)
    at Request._callback (/Applications/Beaker Browser.app/Contents/Resources/app.asar/node_modules/nat-upnp/lib/nat-upnp/device.js:149:14)
    at Request.self.callback (/Applications/Beaker Browser.app/Contents/Resources/app.asar/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/Applications/Beaker Browser.app/Contents/Resources/app.asar/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/Applications/Beaker Browser.app/Contents/Resources/app.asar/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1092:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
objc[47319]: couldn't dlopen libobjc-trampolines.dylib: dlopen(/usr/lib/libobjc-trampolines.dylib, 262): no suitable image found.  Did find:
        /usr/lib/libobjc-trampolines.dylib: file system sandbox blocked stat()
```

**Comment by pfrazee** [comment]
@the-kenny those errors *might* indicate something that's indirectly related but won't be 100% related. It's a background process that's attempting to contact your router's UPnP tools to improve holepunching.

**Comment by rex4539** [comment]
I actually get a crash when opening Preferences in 10.15

[Beaker Browser Helper_2019-09-18-155533_MacBook-Pro-2018.log](https://github.com/beakerbrowser/beaker/files/3626488/Beaker.Browser.Helper_2019-09-18-155533_MacBook-Pro-2018.log)

**Comment by pirate** [comment]
Also getting this as well when attempting to visit any Dat URLs.

<img width="1256" alt="Screen Shot 2019-09-21 at 2 33 50 PM" src="https://user-images.githubusercontent.com/511499/65377634-d8087880-dc7c-11e9-8732-c8652afe7ecc.png">

**Comment by miniak** [comment]
Is this version running on Electron 4 or 5?

**Comment by miniak** [comment]
https://github.com/electron/electron/pull/20497

**Comment by rex4539** [comment]
> Is this version running on Electron 4 or 5?

According to https://github.com/beakerbrowser/beaker/commit/7fa1a0a815ceb9bfc3ec408cd355fd372cfdbf47 it seems to be running Electron 5.

**Comment by miniak** [comment]
The `/usr/lib/libobjc-trampolines.dylib: file system sandbox blocked stat()` crash only affects Electron 4 and lower

**Comment by espace-piins-web** [comment]
I have the same problem. I have two Macs, one with Catalina and the other with Mojave. And he don't work with Catalina. Maybe it's an useless information but I hope it can help to fix it
