### ISSUE TITLE
branch blue-hyperdrive10 doesn't start - missing dependency??

### ISSUE THREAD

**Issue by pmario** [beakerbrowser/beaker#1480]
Operation System: Ubuntu 18.04.3
Beaker version: latest master

I was able to compile all the dependencies. No errors, but npm start says this.

Did I miss a dependency?

```
[mario:~/git/beaker/] upstream#blue-hyperdrive10(+4/-1)+* 5m1s ± 
-> npm start

> beakerbrowser@ start /home/mario/git/beaker
> gulp start

[15:03:11] Using gulpfile ~/git/beaker/gulpfile.js
[15:03:11] Starting 'start'...
[15:03:11] Starting '<anonymous>'...
Spawning electron /home/mario/git/beaker/node_modules/electron/dist/electron
App threw an error during load
Error: Cannot find module './rpc/daemon/corestore_pb.js'
Require stack:
- /home/mario/git/beaker/app/node_modules/hyperdrive-daemon-client/lib/rpc.js
- /home/mario/git/beaker/app/node_modules/hyperdrive-daemon-client/index.js
- /home/mario/git/beaker/app/node_modules/hyperdrive-daemon/index.js
- /home/mario/git/beaker/app/main.build.js
- /home/mario/git/beaker/node_modules/electron/dist/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
    at Function../lib/common/reset-search-paths.ts.Module._resolveFilename (electron/js2c/browser_init.js:7601:16)
    at Module._load (internal/modules/cjs/loader.js:622:27)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:775:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/home/mario/git/beaker/app/node_modules/hyperdrive-daemon-client/lib/rpc.js:15:15)
    at Module._compile (internal/modules/cjs/loader.js:880:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
```

**Comment by pmario** [comment]
used node version 11.15.0

**Comment by pfrazee** [comment]
Hey man, I'm sorry but this branch isn't stable for release so I really don't want to give support on it. Sometimes we allow temporary breaks in the checkin which we know how to workaround.
