### ISSUE TITLE
blue-hyperdrive10: doesn't use running hyperdrive-daemon

### ISSUE THREAD

**Issue by edrex** [beakerbrowser/beaker#1499]
When hyperdrive daemon is already running, i get a non-fatal lock error and no electron window:

```
beaker git/blue-hyperdrive10  169s
❯ npm start      

> beakerbrowser@ start /home/eric/src/github.com/beakerbrowser/beaker
> gulp start

[20:16:57] Using gulpfile ~/src/github.com/beakerbrowser/beaker/gulpfile.js
[20:16:57] Starting 'start'...
[20:16:57] Starting '<anonymous>'...
Spawning electron /home/eric/src/github.com/beakerbrowser/beaker/node_modules/electron/dist/electron
Gtk-Message: 20:16:57.474: Failed to load module "appmenu-gtk-module"
[winston] Attempt to write logs with no transports {"category":"dat","subcategory":"dns","message":"Using dns.google.com to resolve DNS lookups","level":"info"}
info:     Using dns.google.com to resolve DNS lookups {"category":"dat","subcategory":"dns"}
info:     Program start
info:     [PROFILES] Database at version 0; Running 1 migrations {"category":"sqlite"}
info:     [AUDIT-LOG] Database at version 0; Running 1 migrations {"category":"sqlite"}
info:     [SETTINGS] Database at version 0; Running 2 migrations {"category":"sqlite"}
info:     [SITEDATA] Database at version 0; Running 6 migrations {"category":"sqlite"}
info:     [AUDIT-LOG] Database migrations completed without error {"category":"sqlite"}
Starting external process hyperdrive-daemon
info:     [SETTINGS] Database migrations completed without error {"category":"sqlite"}
info:     [PROFILES] Database migrations completed without error {"category":"sqlite"}
info:     [SITEDATA] Database migrations completed without error {"category":"sqlite"}
{"level":30,"time":1579753018879,"pid":855935,"hostname":"chip","name":"hyperdrive","component":"server","msg":"memory only? false telemetry enabled? false","v":1}
Uncaught exception: Error [OpenError]: IO error: lock /home/eric/.hyperdrive/storage/db/LOCK: Resource temporarily unavailable
    at /home/eric/src/github.com/beakerbrowser/beaker/app/node_modules/levelup/lib/levelup.js:119:23
    at /home/eric/src/github.com/beakerbrowser/beaker/app/node_modules/deferred-leveldown/node_modules/abstract-leveldown/abstract-leveldown.js:36:14
    at /home/eric/src/github.com/beakerbrowser/beaker/app/node_modules/deferred-leveldown/deferred-leveldown.js:31:21
    at /home/eric/src/github.com/beakerbrowser/beaker/app/node_modules/encoding-down/node_modules/abstract-leveldown/abstract-leveldown.js:36:14
    at /home/eric/src/github.com/beakerbrowser/beaker/app/node_modules/leveldown/node_modules/abstract-leveldown/abstract-leveldown.js:36:14
{"level":50,"time":1579753018901,"pid":855935,"hostname":"chip","name":"hyperdrive","component":"server","error":{},"msg":"stopping daemon due to error","v":1}
Error: timeout
    at Timeout._onTimeout (/home/eric/src/github.com/beakerbrowser/beaker/app/node_modules/nat-upnp/lib/nat-upnp/client.js:187:14)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```

From Paul's response on chat it sounds like the desired behavior is to proxy through the existing instance.

**Comment by edrex** [comment]
Likely related, after I shut down standalone hyperdrive-daemon and started beaker successfully, I get this error visiting home drive:

![Screenshot-2020-01-24-10:50:53](https://user-images.githubusercontent.com/14615/73095496-9dffeb00-3e97-11ea-93af-4d63137a30e8.png)

**Comment by edrex** [comment]
And then after closing beaker:

```
~/Hyperdrive   
❯ hyperdrive status  
The Hyperdrive daemon is not running.
                                                                                                                                                                                 
~/Hyperdrive   
❯ hyperdrive start 
✔ Hyperdrive daemon listening on localhost:3101
                                                                                                                                                                                 
~/Hyperdrive   
❯ hyperdrive fs mount
Could not mount the drive:
TypeError: Cannot destructure property `path` of 'undefined' or 'null'.
```

**Comment by edrex** [comment]
I just pulled latest and all this is fixed :D

**Comment by pfrazee** [comment]
Nice!
