### ISSUE TITLE
sqlite3 nodejs error

### ISSUE THREAD

**Issue by bit2core** [beakerbrowser/beaker#1500]
Did some has the same error ? Had this error with node v 11 / 12 /13. Looking for help

npm install error result:

```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(209,
5): error MSB6006: "cmd.exe" wurde mit dem Code 1 beendet. [C:\Users\Lenovo\Desktop\beaker-master\app\node_modules\sqli
te3\build\deps\action_before_build.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:193:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:255:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\Lenovo\\Desktop\\beaker-master\\app\\node_modules\\sqlite3\\lib\\binding\\electron-v5.0-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=C:\\Users\\Lenovo\\Desktop\\beaker-master\\app\\node_modules\\sqlite3\\lib\\binding\\electron-v5.0-win32-x64" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=electron-v5.0"
gyp ERR! cwd C:\Users\Lenovo\Desktop\beaker-master\app\node_modules\sqlite3
gyp ERR! node -v v11.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\Lenovo\Desktop\beaker-master\app\node_modules\sqlite3\lib\binding\electron-v5.0-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Users\Lenovo\Desktop\beaker-master\app\node_modules\sqlite3\lib\binding\electron-v5.0-win32-x64 --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v5.0' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Lenovo\Desktop\beaker-master\app\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:193:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:999:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
node-pre-gyp ERR! System Windows_NT 10.0.18362
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Lenovo\\Desktop\\beaker-master\\app\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\Lenovo\Desktop\beaker-master\app\node_modules\sqlite3
node-pre-gyp ERR! node -v v11.15.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\Lenovo\Desktop\beaker-master\app\node_modules\sqlite3\lib\binding\electron-v5.0-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Users\Lenovo\Desktop\beaker-master\app\node_modules\sqlite3\lib\binding\electron-v5.0-win32-x64 --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v5.0' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@4.1.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@4.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Lenovo\AppData\Roaming\npm-cache\_logs\2020-01-25T16_30_07_514Z-debug.log
npm run build

> beakerbrowser@ build C:\Users\Lenovo\Desktop\beaker-master
> gulp build
```
npm run rebuild 
npm start error result:
```
App threw an error during load
Error: Cannot find module 'C:\Users\Lenovo\Desktop\beaker-master\app\node_modules\sqlite3\lib\binding\electron-v5.0-win32-x64\node_sqlite3.node'
Require stack:
- C:\Users\Lenovo\Desktop\beaker-master\app\node_modules\sqlite3\lib\sqlite3.js
- C:\Users\Lenovo\Desktop\beaker-master\app\node_modules\@beaker\core\dbs\sitedata.js
- C:\Users\Lenovo\Desktop\beaker-master\app\node_modules\@beaker\core\dat\library.js
- C:\Users\Lenovo\Desktop\beaker-master\app\node_modules\@beaker\core\dat\debugging.js
- C:\Users\Lenovo\Desktop\beaker-master\app\node_modules\@beaker\core\dat\index.js
- C:\Users\Lenovo\Desktop\beaker-master\app\node_modules\@beaker\core\index.js
- C:\Users\Lenovo\Desktop\beaker-master\app\background-process.build.js
- C:\Users\Lenovo\Desktop\beaker-master\node_modules\electron\dist\resources\default_app.asar\main.js
-
    at Module._resolveFilename (internal/modules/cjs/loader.js:659:15)
    at Function.Module._resolveFilename (C:\Users\Lenovo\Desktop\beaker-master\node_modules\electron\dist\resources\electron.asar\common\reset-search-paths.js:43:12)
    at Function.Module._load (internal/modules/cjs/loader.js:577:27)
    at Module.require (internal/modules/cjs/loader.js:715:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (C:\Users\Lenovo\Desktop\beaker-master\app\node_modules\sqlite3\lib\sqlite3.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:808:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:820:10)
    at Module.load (internal/modules/cjs/loader.js:677:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:609:12)
```

Operation System: Windows  10
Python 2.7.11 (64bit)
Node.js 11.15.0 
Visual Studio 2017
Beaker version: 0.8.8 (newest)

**Comment by pfrazee** [comment]
You need to run `npm run rebuild` after `npm install` to get native modules to build for the correct dependency, per the [readme instructions](https://github.com/beakerbrowser/beaker#building-from-source).

**Comment by bit2core** [comment]
done exactly in the way as the instructions. Even today on a complete clean windows 10 64Bit Maschine. Same errors

**Comment by bit2core** [comment]
> You need to run `npm run rebuild` after `npm install` to get native modules to build for the correct node version, per the [readme instructions](https://github.com/beakerbrowser/beaker#building-from-source).

Thanks for your fast answer but not solving my problem.

**Comment by pfrazee** [comment]
Apologies! I read your issue too quickly. Looks like sqlite is failing to build.

I haven't built on Windows recently. Did you go through the prerequisites bit, including the windows-build-tools?

**Comment by hossameldeen** [comment]
I have the same start error but I'm not building from source.

**OS:** Windows 10.  
**Beaker version:** Was on 0.8.8. Updated to 0.8.9 through the automatic update. Restarted and got this error.

![image](https://user-images.githubusercontent.com/6719916/76595463-5810ec00-6504-11ea-97b0-3382cd68bf65.png)

**Comment by hans1337** [comment]
Interesting I have the same problem and error message
