### ISSUE TITLE
blue-hyperdrive10: with pre-existing `~/.hyperdrive` folder, hyperdrive daemon fails mysteriously

### ISSUE THREAD

**Issue by micahscopes** [beakerbrowser/beaker#1510]
For the longest time, I've been very confused about why I couldn't start Beaker Blue.  Turns out, it was because I had an existing `~/.hyperdrive` directory!  After deleting it, Beaker starts just fine.

Maybe this could be an area for some improved error handling?

#### Before deleting `~/.hyperdrive`

When I did `➜ npm run start`, I got:
```
Spawning electron /home/micah/Programs/beaker-git/src/beaker/node_modules/electron/dist/electron
[winston] Attempt to write logs with no transports {"category":"hyper","subcategory":"dns","message":"Using cloudflare-dns.com to resolve DNS lookups","level":"info"}
[winston] Attempt to write logs with no transports {"category":"hyper","subcategory":"dns","message":"Using cloudflare-dns.com to resolve DNS lookups","level":"info"}
info:     Using cloudflare-dns.com to resolve DNS lookups {"category":"hyper","subcategory":"dns"}
info:     Using cloudflare-dns.com to resolve DNS lookups {"category":"hyper","subcategory":"dns"}
info:     Program start
Failed to connect to an external daemon. Launching the daemon...
Failed to connect to daemon, retrying Error: Failed to connect before the deadline
    at checkState (/home/micah/Programs/beaker-git/src/beaker/app/node_modules/@grpc/grpc-js/build/src/client.js:49:26)
    at Timeout._onTimeout (/home/micah/Programs/beaker-git/src/beaker/app/node_modules/@grpc/grpc-js/build/src/channel.js:294:17)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7) {
  disconnected: true
}
Failed to connect to daemon, retrying Error: Failed to connect before the deadline
    at checkState (/home/micah/Programs/beaker-git/src/beaker/app/node_modules/@grpc/grpc-js/build/src/client.js:49:26)
    at Timeout._onTimeout (/home/micah/Programs/beaker-git/src/beaker/app/node_modules/@grpc/grpc-js/build/src/channel.js:294:17)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7) {
  disconnected: true
}
Failed to connect to daemon, retrying Error: Failed to connect before the deadline
    at checkState (/home/micah/Programs/beaker-git/src/beaker/app/node_modules/@grpc/grpc-js/build/src/client.js:49:26)
    at Timeout._onTimeout (/home/micah/Programs/beaker-git/src/beaker/app/node_modules/@grpc/grpc-js/build/src/channel.js:294:17)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7) {
  disconnected: true
}
...
```
Using `➜ pm2 logs` showed:
```
PM2      | App [hyperdrive:0] starting in -fork mode-
PM2      | App [hyperdrive:0] online
0|hyperdrive  | {"level":30,"time":1581808376113,"pid":18489,"hostname":"slab-of-metal","name":"hyperdrive","component":"server","msg":"memory only? false telemetry enabled? false","v":1}
0|hyperdrive  | {"level":30,"time":1581808376141,"pid":18489,"hostname":"slab-of-metal","name":"hyperdrive","component":"server","seed":"d09ae6dbcbdf6d67a8dd507f43889dec757a3de59ab5ae5d4e13b81b6866cc97","msg":"creating replication keypair","v":1}
0|hyperdrive  | {"level":50,"time":1581808376162,"pid":18489,"hostname":"slab-of-metal","name":"hyperdrive","component":"server","error":true,"err":{"type":"Error","message":"Unexpected end of JSON input","stack":"EncodingError: Unexpected end of JSON input
    at /home/micah/Programs/beaker-git/src/beaker/app/node_modules/encoding-down/index.js:138:17
    at /home/micah/Programs/beaker-git/src/beaker/app/node_modules/subleveldown/node_modules/abstract-leveldown/abstract-iterator.js:31:14
    at /home/micah/Programs/beaker-git/src/beaker/app/node_modules/subleveldown/leveldown.js:34:8
    at /home/micah/Programs/beaker-git/src/beaker/app/node_modules/leveldown/node_modules/abstract-leveldown/abstract-iterator.js:31:14
    at processTicksAndRejections (internal/process/task_queues.js:81:21)"},"message":"Unexpected end of JSON input","stack":"EncodingError: Unexpected end of JSON input
    at /home/micah/Programs/beaker-git/src/beaker/app/node_modules/encoding-down/index.js:138:17
    at /home/micah/Programs/beaker-git/src/beaker/app/node_modules/subleveldown/node_modules/abstract-leveldown/abstract-iterator.js:31:14
    at /home/micah/Programs/beaker-git/src/beaker/app/node_modules/subleveldown/leveldown.js:34:8
    at /home/micah/Programs/beaker-git/src/beaker/app/node_modules/leveldown/node_modules/abstract-leveldown/abstract-iterator.js:31:14
    at processTicksAndRejections (internal/process/task_queues.js:81:21)","msg":"stopping daemon due to error","v":1}
0|hyperdrive  | {"level":30,"time":1581808376162,"pid":18489,"hostname":"slab-of-metal","name":"hyperdrive","component":"server","msg":"stopping telemetry if telemetry is running","v":1}
0|hyperdrive  | {"level":30,"time":1581808376162,"pid":18489,"hostname":"slab-of-metal","name":"hyperdrive","component":"server","msg":"waiting for fuse to unmount","v":1}
0|hyperdrive  | {"level":30,"time":1581808376162,"pid":18489,"hostname":"slab-of-metal","name":"hyperdrive","component":"server","msg":"waiting for networking to close","v":1}
0|hyperdrive  | {"level":30,"time":1581808376163,"pid":18489,"hostname":"slab-of-metal","name":"hyperdrive","component":"server","msg":"waiting for corestore to close","v":1}
0|hyperdrive  | {"level":30,"time":1581808376163,"pid":18489,"hostname":"slab-of-metal","name":"hyperdrive","component":"server","msg":"waiting for db to close","v":1}
PM2           | App [hyperdrive:0] exited with code [0] via signal [SIGINT]
```

Operation System: Arch Linux x86 64 bit

Beaker version: blue-hyperdrive10

**Comment by pfrazee** [comment]
Hey, yeah this is *probably* due to changes happening in the daemon due to it being a prerelease, but I agree the error diagnostics for the daemon need to be much better.
