### ISSUE TITLE
TypeError: spellchecker.setDictionary is not a function

### ISSUE THREAD

**Issue by almereyda** [beakerbrowser/beaker#1531]
Operation System: Fedora 30
Beaker version: #1435 1677c5f9c58aee1aa1cab72ec3398f17d47c9371
Node: 10.15.3 (+ 12.16.1)
NPM: 6.9.0 (6.14.3)

When running `npm install`, `npm run rebuild` and `npm start` from the `blue-hyperdrive10` branch, the console throws the following error, next to others:

```
Detected Linux. Setting up spell check for Linux.
Unhandled Rejection at: Promise Promise {
  <rejected> TypeError: spellchecker.setDictionary is not a function
      at setupLinux (/home/yala/src/github.com/beakerbrowser/beaker/app/main.build.js:13746:22)
      at setup$t (/home/yala/src/github.com/beakerbrowser/beaker/app/main.build.js:13731:9)
      at App.<anonymous> (/home/yala/src/github.com/beakerbrowser/beaker/app/main.build.js:15395:3)
} reason: TypeError: spellchecker.setDictionary is not a function
    at setupLinux (/home/yala/src/github.com/beakerbrowser/beaker/app/main.build.js:13746:22)
    at setup$t (/home/yala/src/github.com/beakerbrowser/beaker/app/main.build.js:13731:9)
    at App.<anonymous> (/home/yala/src/github.com/beakerbrowser/beaker/app/main.build.js:15395:3)
error:    Unhandled Rejection at: Promise [object Promise] reason: TypeError: spellchecker.setDictionary is not a function {"category":"browser"}
Hyperdrive daemon has been restored
```

Then nothing happens, and no UI appears, as one could expect.

**Comment by pfrazee** [comment]
Okay this should be solved in latest commit (0eab861832ee0aec72321aba0f16fc3056487cf0)
