### ISSUE TITLE
Cannot Explore Files On My Own Profile

### ISSUE THREAD

**Issue by theorangepotato** [beakerbrowser/beaker#1573]
**Describe the bug**
After experiencing #1568, I built Beaker from source following [the instructions](https://github.com/beakerbrowser/beaker#building-from-source). This led to a new error whereby I could successfully access the `File Explorer` and `Editor` for hyperdrives I do not control, however, as soon as I clicked on `Explore Files` on my profile, it would not load. It seemed to crash my ability to interact with my own profile. I could no longer refresh the page and my profile photo disappeared from the new tab page. Additionally, when I quit Beaker, it exited very loudly, throwing a lot of errors. The errors from shutting down Beaker can be found [here](https://github.com/beakerbrowser/beaker/files/4631600/error.txt).

Judging by the last errors though, it seems to be an issue with gRPC's call-stream?

If I do not click on `Explore Files` while on my profile, even if I click it while on another hyperdrive, Beaker allows me to explore the hyperdrive's files and exits cleanly.

**To Reproduce**
1. Be running Linux
2. Run the Beaker AppImage (I do not know if this part is necessary or not)
3. Create a new profile in the start up flow
4. Build Beaker from source
5. Run this newly built Beaker from the terminal
6. Wait a minute or two (it seems to sometimes work if you try quickly after launch)
7. Navigate to your profile page
8. Click `Explore Files` (it will show `Loading...` instead of files)
9. Unsuccessfully try to refresh page
10. Open new tab to see your profile photo is gone (refresh this page if the photo is cached)
11. Quit Beaker (many errors will flood the terminal)

**Expected behavior**
I should be able to view and explore the files of my own hyperdrive using the `Explore Files` button, and I should continue to be able to access my profile page even after clicking the button.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Version: Built when master was at c877168836544333a2e166fc478ae7effa8a3c0a

**Additional context**
I was able to reproduce this several times, but it seems to sometimes work if I try quickly after launch. I don't know if it is truly a time delay, or a small sample size combined with some sort of race condition that only shows up periodically.

**Comment by pfrazee** [comment]
So this seems like a separate issue from the AppImage one, it occurs when you run from source, and is triggered by clicking Explore Files?

**Comment by theorangepotato** [comment]
> So this seems like a separate issue from the AppImage one

I assumed so, which is why I filed a new bug. But, I wanted to provide full context since the profile was originally created in the AppImage

> it occurs when you run from source, and is triggered by clicking Explore Files?

Yes, exactly. I have no problems if I never click the button, or only click it on other people's hyperdrives, and I also don't seem to have problems if I click it on my own profile quickly after launch. It's a weird bug.

Let me know if I can provide any other information! I'm happy to help test or triage.

**Comment by pfrazee** [comment]
@theorangepotato could you try pulling latest on master, running an `npm run burnthemall` and starting again? If that doesn't work can you tell me if you ran any version of beaker in the `blue-hyperdrive10` branch over the last year?

**Comment by theorangepotato** [comment]
> could you try pulling latest on master, running an `npm run burnthemall` and starting again?

Sadly, I am still getting this error. I even tried deleting the repo and recloning it just to make extra sure. Though I am still using the same profile.

> If that doesn't work can you tell me if you ran any version of beaker in the `blue-hyperdrive10` branch over the last year?

I have not. The last version of Beaker that I ran was `Beaker.Browser-0.8.10.AppImage`, but this profile was generated on `Beaker.Browser-1.0.0-prerelease.1.AppImage`

Interestingly, this all does *not* seem to be a problem with `Beaker.Browser-1.0.0-prerelease.1-and-a-half.AppImage`. I have been using the new AppImage successfully and not running into any of these issues. Another difference I have found between them is that when I build from source, the `Hyperdrive/` FUSE folder does not successfully mount, but when I run the AppImage, it does. I wonder if this is related?

Would it be helpful if I deleted/moved all of my state, like the `Beaker Browser/` and `.hyperdrive/` folders, to confirm that there is no old state or malformed data structure?

**Comment by pfrazee** [comment]
> Interestingly, this all does not seem to be a problem with Beaker.Browser-1.0.0-prerelease.1-and-a-half.AppImage.

Okay now *that* is bizarre. I feel like if that AppImage is working, we shouldnt need to nuke all your data. Is there any chance that your build is failing somewhere?

**Comment by theorangepotato** [comment]
> Okay now `that` is bizarre.

I agree!

> Is there any chance that your build is failing somewhere?

Okay, so I've cleanly rebuilt it, and I get two errors during the `npm install` step, but none during the `npm run rebuild` step. The two errors are:
```js
../src/async.cc: In constructor ‘SetWorker::SetWorker(v8::Local<v8::Value>, v8::Local<v8::Value>, v8::Local<v8::Value>, Nan::Callback*)’:
../src/async.cc:52:55: error: no matching function for call to ‘v8::Value::ToObject()’
   52 |     v8::Local<v8::Object> bufferObj = value->ToObject();
      |                                                       ^
```

and

```js
make: *** [xattr.target.mk:115: Release/obj.target/xattr/src/async.o] Error 1
make: Leaving directory '$PATH_TO_BEAKER/Beaker/beaker/scripts/node_modules/fs-xattr/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit ($PATH_TO_NODE/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.4.0-29-generic
gyp ERR! command "$PATH_TO_BIN/node" "$PATH_TO_NODE/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd $PATH_TO_BEAKER/Beaker/beaker/scripts/node_modules/fs-xattr
gyp ERR! node -v v12.16.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 

```
I have confirmed that I have all of the listed dependencies for Debian/Ubuntu. And for completeness:
**Node version**: v12.16.3
**NPM version**: 6.14.4

When I stop the Beaker that I built from source (cleanly, not trying to reproduce the broken profile bug above), I get the following error:
```js
2020-05-20T10:35:33: PM2 log: Stopping app:hyperdrive id:0
2020-05-20T10:35:33: PM2 error: Uncaught exception: Error: 1 CANCELLED: Call cancelled
    at Object.callErrorFromStatus ($PATH_TO_BEAKER/Beaker/beaker/app/node_modules/@grpc/grpc-js/build/src/call.js:30:26)
    at Object.onReceiveStatus ($PATH_TO_BEAKER/Beaker/beaker/app/node_modules/@grpc/grpc-js/build/src/client.js:390:49)
    at Object.onReceiveStatus ($PATH_TO_BEAKER/Beaker/beaker/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:304:181)
    at Http2CallStream.outputStatus ($PATH_TO_BEAKER/Beaker/beaker/app/node_modules/@grpc/grpc-js/build/src/call-stream.js:115:74)
    at Http2CallStream.maybeOutputStatus ($PATH_TO_BEAKER/Beaker/beaker/app/node_modules/@grpc/grpc-js/build/src/call-stream.js:154:22)
    at Http2CallStream.endCall ($PATH_TO_BEAKER/Beaker/beaker/app/node_modules/@grpc/grpc-js/build/src/call-stream.js:140:18)
    at ClientHttp2Stream.<anonymous> ($PATH_TO_BEAKER/Beaker/beaker/app/node_modules/@grpc/grpc-js/build/src/call-stream.js:396:22)
    at ClientHttp2Stream.emit (events.js:223:5)
    at ClientHttp2Stream.EventEmitter.emit (domain.js:475:20)
    at emitCloseNT (internal/streams/destroy.js:69:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:61:3)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  code: 1,
  details: 'Call cancelled',
  metadata: Metadata { internalRepr: Map {}, options: {} }
}
error:    Uncaught exception: Error: 1 CANCELLED: Call cancelled {"category":"browser"}
2020-05-20T10:35:33: PM2 log: App [hyperdrive:0] exited with code [0] via signal [SIGINT]
2020-05-20T10:35:33: PM2 log: pid=157273 msg=process killed
info:     Program quit {"category":"browser","subcategory":"init"}
[10:35:33] The following tasks did not complete: start, <anonymous>
[10:35:33] Did you forget to signal async completion?
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! beakerbrowser@ start: `gulp start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the beakerbrowser@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

which points to a log that states:

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '$PATH_TO_BIN/node',
1 verbose cli   '$PATH_TO_BIN/npm',
1 verbose cli   'run',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v12.16.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle beakerbrowser@~prestart: beakerbrowser@
6 info lifecycle beakerbrowser@~start: beakerbrowser@
7 verbose lifecycle beakerbrowser@~start: unsafe-perm in lifecycle true
8 verbose lifecycle beakerbrowser@~start: PATH: $CENSORED
9 verbose lifecycle beakerbrowser@~start: CWD: $PATH_TO_BEAKER/Beaker/beaker/scripts
10 silly lifecycle beakerbrowser@~start: Args: [ '-c', 'gulp start' ]
11 silly lifecycle beakerbrowser@~start: Returned: code: 1  signal: null
12 info lifecycle beakerbrowser@~start: Failed to exec start script
13 verbose stack Error: beakerbrowser@ start: `gulp start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> ($PATH_TO_NODE/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:310:20)
13 verbose stack     at ChildProcess.<anonymous> ($PATH_TO_NODE/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:310:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid beakerbrowser@
15 verbose cwd /$PATH_TO_BEAKER/Beaker/beaker/scripts
16 verbose Linux 5.4.0-29-generic
17 verbose argv "$PATH_TO_BIN/node" "$PATH_TO_BIN/npm" "run" "start"
18 verbose node v12.16.3
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error beakerbrowser@ start: `gulp start`
22 error Exit status 1
23 error Failed at the beakerbrowser@ start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

I hope this is helpful! I also hope I'm helping find an actual bug and not just a quirk of my system! 😬

(PS I have minimally censored the above logs. I don't believe I scrubbed any relevant info, but let me know if there's an issue)
