### ISSUE TITLE
Can't edit my hyperdrive

### ISSUE THREAD

**Issue by rzelnik** [beakerbrowser/beaker#1584]
When I start Beaker from source code (commit Update issue templates), it works well. When I start Beaker from AppImage, I can not edit my own hyperdrive. It shows a source code of any read-only hyperdrive or a source code of a remote https-website, but when I want to edit my own hyperdrive, the edit window only shows "Select a file". When I click on it the file tree appears. I can click on any file, the edit window still shows a "Select a file" message. After this, the same issue appears also on Beaker started from source code.

**To Reproduce**
1. Start Beaker Browser on Ubuntu 20.04 from AppImage
2. Click on your profile (or any other self-owned hyperdrive)
3. Click on Editor (Left Upper corner) and select any file (for example index.html)
4. See "Select a file"

It shows this error mesages:

```
$ npm start

> beakerbrowser@ start /home/rzelnik/Software/desktop/Beaker_Browser/beaker-source/scripts
> gulp start

[16:49:39] Using gulpfile ~/Software/desktop/Beaker_Browser/beaker-source/scripts/gulpfile.js
[16:49:39] Starting 'start'...
[16:49:39] Starting '<anonymous>'...
Spawning electron /home/rzelnik/Software/desktop/Beaker_Browser/beaker-source/scripts/node_modules/electron/dist/electron
[16:49:40] The following tasks did not complete: start, <anonymous>
[16:49:40] Did you forget to signal async completion?
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! beakerbrowser@ start: `gulp start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the beakerbrowser@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/rzelnik/.npm/_logs/2020-05-15T14_49_40_912Z-debug.log
```
cat /home/rzelnik/.npm/_logs/2020-05-15T14_49_40_912Z-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.14.4
3 info using node@v14.2.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle beakerbrowser@~prestart: beakerbrowser@
6 info lifecycle beakerbrowser@~start: beakerbrowser@
7 verbose lifecycle beakerbrowser@~start: unsafe-perm in lifecycle true
8 verbose lifecycle beakerbrowser@~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/rzelnik/Software/desktop/Beaker_Browser/beaker-source/scripts/node_modules/.bin:/home/rzelnik/.yarn/bin:/home/rzelnik/.config/yarn/global/node_modules/.bin:/home/rzelnik/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle beakerbrowser@~start: CWD: /home/rzelnik/Software/desktop/Beaker_Browser/beaker-source/scripts
10 silly lifecycle beakerbrowser@~start: Args: [ '-c', 'gulp start' ]
11 silly lifecycle beakerbrowser@~start: Returned: code: 1  signal: null
12 info lifecycle beakerbrowser@~start: Failed to exec start script
13 verbose stack Error: beakerbrowser@ start: `gulp start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1051:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid beakerbrowser@
15 verbose cwd /home/rzelnik/Software/desktop/Beaker_Browser/beaker-source/scripts
16 verbose Linux 5.4.0-29-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v14.2.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error beakerbrowser@ start: `gulp start`
22 error Exit status 1
23 error Failed at the beakerbrowser@ start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Expected behavior**
My own files should be editable.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Beaker Browser
 - Version 1.0.0-prerelease.1

**Comment by pfrazee** [comment]
I think this is the same AppImage issue that everybody is having, see https://github.com/beakerbrowser/beaker/issues/1568

Closing as a dup, reopen if I'm wrong!
