### ISSUE TITLE
Editor doesn't work, always says "Select a file"

### ISSUE THREAD

**Issue by jes** [beakerbrowser/beaker#1594]
**Describe the bug**
The Editor pane always says "Select a file" and never lets me edit anything.

**To Reproduce**
I open up the editor window on my personal page (?) and select any file (e.g. index.html) in the editor pane, but still all I see in the editor pane is a link saying "Select a file", if I start Beaker from the terminal I see a bunch of:

```
error:    Uncaught exception: TypeError: cb is not a function {"category":"browser"}
2020-05-15T20:06:57: PM2 error: Uncaught exception: TypeError: cb is not a function
    at /tmp/.mount_BeakerGuSAhF/resources/app/node_modules/call-me-maybe/index.js:11:28
    at processTicksAndRejections (internal/process/task_queues.js:76:11)
```

**Expected behavior**
I expected the editor pane to have some HTML in it, or at least let me write some HTML in it.

**Screenshots**
![Screenshot from 2020-05-15 20-09-21](https://user-images.githubusercontent.com/297425/82087437-fdecfc80-96e7-11ea-80a8-f8a0d276d6a4.png)

**Desktop (please complete the following information):**
Ubuntu 20.04, running the latest BeakerBrowser 1.0 beta AppImage

**Comment by jes** [comment]
Possibly related to #1568

**Comment by jes** [comment]
Seems same as #1584, closing
