### ISSUE TITLE
dat -> hyperdrive converter fails on Windows with Error: /C: could not be found 

### ISSUE THREAD

**Issue by cryptowyrm** [beakerbrowser/beaker#1611]
**Describe the bug**
When using the dat -> hyperdrive converter in Beaker on Windows (doesn't happen on Linux with the same Dat archives), the files listing is shown as empty and after clicking the "convert" button, it creates a new hyperdrive but the only file is a `index.json` with empty curly brackets inside, no other files are created. When starting Beaker from PowerShell, it shows the error `Error: /C: could not be found` after clicking on the "convert" button.

**To Reproduce**
1. Open Beaker
2. Scroll down to the legacy Dat to hyperdrive converter section on the New Tab page
3. Click on any of the archives
4. Click on convert button
5. Mostly empty hyperdrive opens, error in console: Error: /C: could not be found

**Expected behavior**
A new hyperdive is created with all the files from the old Dat archive inside.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Beaker Browser 1.0 pre-release

**Additional context**
The full error shown in the console after clicking the "convert" button on a legacy Dat archive:

```
(node:19660) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(node:19660) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Sparse-file support not detected. Falling back to indexed data files.
(node:19660) UnhandledPromiseRejectionWarning: Error: /C: could not be found
    at notFound (C:\Users\serio\AppData\Local\Programs\beaker-browser\resources\app\bg\dat\converter\node_modules\append-tree\index.js:683:13)
    at onnodes (C:\Users\serio\AppData\Local\Programs\beaker-browser\resources\app\bg\dat\converter\node_modules\append-tree\index.js:116:36)
    at onget (C:\Users\serio\AppData\Local\Programs\beaker-browser\resources\app\bg\dat\converter\node_modules\append-tree\index.js:358:21)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(node:19660) UnhandledPromiseRejectionWarning: Error: /C: could not be found
    at notFound (C:\Users\serio\AppData\Local\Programs\beaker-browser\resources\app\bg\dat\converter\node_modules\append-tree\index.js:683:13)
    at onnodes (C:\Users\serio\AppData\Local\Programs\beaker-browser\resources\app\bg\dat\converter\node_modules\append-tree\index.js:116:36)
    at onget (C:\Users\serio\AppData\Local\Programs\beaker-browser\resources\app\bg\dat\converter\node_modules\append-tree\index.js:358:21)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(node:19660) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:19660) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:19660) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:19660) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by pfrazee** [comment]
Interesting! Thanks for filing, I'll check into this.

**Comment by cryptowyrm** [comment]
@pfrazee I'm afraid in 1.0.0-prerelease.2 the issue is still there, but the error message changed to a missing module, maybe it didn't get packaged with the installer or the path is wrong:

```
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module '@beaker/dat-legacy-tools/bin.js'
Require stack:
- C:\Users\serio\AppData\Local\Programs\beaker-browser\resources\app\bg\dat\converter\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at Module._load (internal/modules/cjs/loader.js:690:27)
    at Module._load (electron/js2c/asar.js:738:28)
    at Function.Module._load (electron/js2c/asar.js:738:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\serio\AppData\Local\Programs\beaker-browser\resources\app\bg\dat\converter\index.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
    at Module.load (internal/modules/cjs/loader.js:815:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\serio\\AppData\\Local\\Programs\\beaker-browser\\resources\\app\\bg\\dat\\converter\\index.js'
  ]
}
```

**Comment by pfrazee** [comment]
Ohhh what a bummer. I must have biffed the packaging on Windows, and I only tested the dat converter on mac. So sorry. On my TODOs.
