### ISSUE TITLE
npm run rebuild sqlite3 problems (windows)

### ISSUE THREAD

**Issue by hans1337** [beakerbrowser/beaker#1615]
```
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  unpack_sqlite_dep
  'C:\Python27' is not recognized as an internal or external command,
  operable program or batch file.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\v140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exi
ted with code 1. [C:\users\hans\Desktop\beaker-master\app\node_modules\sqlite3\build\deps\action_before_build.v
cxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:191:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\users\\hans\\Desktop\\beaker-master\\app\\node_modules\\sqlite3\\lib\\binding\\electron-v9.0-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=C:\\users\\hans\\Desktop\\beaker-master\\app\\node_modules\\sqlite3\\lib\\binding\\electron-v9.0-win32-x64" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=electron-v9.0"
gyp ERR! cwd C:\users\hans\Desktop\beaker-master\app\node_modules\sqlite3
gyp ERR! node -v v10.20.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\users\hans\Desktop\beaker-master\app\node_modules\sqlite3\lib\binding\electron-v9.0-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\users\hans\Desktop\beaker-master\app\node_modules\sqlite3\lib\binding\electron-v9.0-win32-x64 --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v9.0' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\hans\Desktop\beaker-master\app\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Windows_NT 10.0.18363
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\hans\\Desktop\\beaker-master\\app\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\users\hans\Desktop\beaker-master\app\node_modules\sqlite3
node-pre-gyp ERR! node -v v10.20.1
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\users\hans\Desktop\beaker-master\app\node_modules\sqlite3\lib\binding\electron-v9.0-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\users\hans\Desktop\beaker-master\app\node_modules\sqlite3\lib\binding\electron-v9.0-win32-x64 --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v9.0' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@4.2.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@4.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
Visual Studio 2017 installed
Windows-build-tools installed
Tested with node 12.16.3 and also node 10.20.1
Installed Python 2.7
Done:
npm config set python c:/python27
npm config set msvs_version 2015
npm install -g node-gyp
npm install -g gulp

Can't get it to work under Windows 10 64x

**Comment by hans1337** [comment]
Same error message, if I do npm start after rebuild
https://github.com/beakerbrowser/beaker/issues/1500#issuecomment-598571631
