### ISSUE TITLE
Beaker won't start (`TypeError: pda.setInvalidAuthHandler`)

### ISSUE THREAD

**Issue by micahscopes** [beakerbrowser/beaker#1736]
Beaker won't start.

```
Unhandled Rejection at: Promise [object Promise] reason: TypeError: pda.setInvalidAuthHandler is not a function TypeError: pda.setInvalidAuthHandler is not a function at setup$4 (/usr/share/beaker-browser/resources/app/main.build.js:2594:9) at Object.setup$n [as setup] (/usr/share/beaker-browser/resources/app/main.build.js:12195:9) at Object.setup (/usr/share/beaker-browser/resources/app/main.build.js:12983:23) at App. (/usr/share/beaker-browser/resources/app/main.build.js:16848:15) [error]
```

**Environment**
 - OS: Linux
 - Beaker Version: [this one](https://github.com/beakerbrowser/beaker/commit/cb83bbd3f4b864f0755c9371b43b7f09fe47d88b)

**Additional Context**
I tried deleting my Beaker data folder, still no luck.

**Comment by Michael-S** [comment]
For what it's worth, I saw the same error on master branch a few weeks ago, but either some interim commit or some package manager upgrade to my copy of node or npm must have fixed it.  Both branch master and branch 1.0-prerelease-5 build and run fine for me now.
Debian Linux x86_64, kernel 5.6, node 12.13.1, npm 6.14.5.

@micahscopes  please try again?
