### ISSUE TITLE
Error: Can't walk dependency graph: Cannot find module '@beaker/dat-serve-resolve-path' f

### ISSUE THREAD

**Issue by PREKNOWLEDGEWEB** [beakerbrowser/beaker#1950]
when running
npm run rebuild

**Comment by fesenden** [comment]
👍👍

**Comment by solarkraft** [comment]
Same. Here's the output: 

```
npx gulp build
[01:43:58] Using gulpfile ~/Documents/Code/Misc/nomad/scripts/gulpfile.js
[01:43:58] Starting 'build'...
[01:43:58] Starting 'bundle'...
[01:43:58] Starting 'bundleTask'...
'listCache' is not exported by '../app/bg/hyper/dns.js'
[01:43:59] 'bundleTask' errored after 1.23 s
[01:43:59] Error: Can't walk dependency graph: Cannot find module '@beaker/dat-serve-resolve-path' from '/Users/paul/Documents/Code/Misc/nomad/app/_stream_0.js'
    required by /Users/paul/Documents/Code/Misc/nomad/app/_stream_0.js
    at /Users/paul/Documents/Code/Misc/nomad/scripts/node_modules/resolve/lib/async.js:146:35
    at processDirs (/Users/paul/Documents/Code/Misc/nomad/scripts/node_modules/resolve/lib/async.js:299:39)
    at isdir (/Users/paul/Documents/Code/Misc/nomad/scripts/node_modules/resolve/lib/async.js:306:32)
    at /Users/paul/Documents/Code/Misc/nomad/scripts/node_modules/resolve/lib/async.js:34:69
    at FSReqCallback.oncomplete (node:fs:198:21)
    at FSReqCallback.callbackTrampoline (node:internal/async_hooks:130:17)
[01:43:59] 'bundle' errored after 1.23 s
[01:43:59] 'build' errored after 1.23 s
```
