### ISSUE TITLE
failed to build from source

### ISSUE THREAD

**Issue by serapath** [beakerbrowser/beaker#239]
Operation System: Linux Mint 17.3
Beaker Version: newest? (2017-01-01)

Just followed the instructions on the `readme` and it threw an error while trying to run `npm run rebuild`

```bash
...
...
make: Entering directory `/home/serapath/Desktop/beaker/app/node_modules/node-webcrypto-ossl/build'
  CXX(target) Release/obj.target/nodessl/src/main.o
In file included from ../src/node/../core/common.h:7:0,
                 from ../src/node/common.h:4,
                 from ../src/main.cpp:1:
../src/node/../core/scoped_ssl.h:6:25: fatal error: openssl/aes.h: No such file or directory
 #include <openssl/aes.h>
                         ^
compilation terminated.
make: *** [Release/obj.target/nodessl/src/main.o] Error 1
make: Leaving directory `/home/serapath/Desktop/beaker/app/node_modules/node-webcrypto-ossl/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/serapath/.nvm/versions/node/v5.11.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 3.19.0-32-generic
gyp ERR! command "/home/serapath/.nvm/versions/node/v5.11.0/bin/node" "/home/serapath/.nvm/versions/node/v5.11.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/serapath/Desktop/beaker/app/node_modules/node-webcrypto-ossl
gyp ERR! node -v v5.11.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

npm ERR! Linux 3.19.0-32-generic
npm ERR! argv "/home/serapath/.nvm/versions/node/v5.11.0/bin/node" "/home/serapath/.nvm/versions/node/v5.11.0/bin/npm" "rebuild" "--runtime=electron" "--target=1.4.6" "--disturl=https://atom.io/download/atom-shell" "--build-from-source"
npm ERR! node v5.11.0
npm ERR! npm  v4.0.3
npm ERR! code ELIFECYCLE
npm ERR! node-webcrypto-ossl@1.0.16 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-webcrypto-ossl@1.0.16 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-webcrypto-ossl package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-webcrypto-ossl
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-webcrypto-ossl
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/serapath/Desktop/beaker/app/npm-debug.log
fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/home/serapath/Desktop/beaker/node_modules/electron/path.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.<anonymous> (/home/serapath/Desktop/beaker/node_modules/electron/index.js:4:42)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)

npm ERR! Linux 3.19.0-32-generic
npm ERR! argv "/home/serapath/.nvm/versions/node/v5.11.0/bin/node" "/home/serapath/.nvm/versions/node/v5.11.0/bin/npm" "run" "rebuild"
npm ERR! node v5.11.0
npm ERR! npm  v4.0.3
npm ERR! code ELIFECYCLE
npm ERR! @ rebuild: `(cd app && npm rebuild --runtime=electron --target=1.4.6 --disturl=https://atom.io/download/atom-shell --build-from-source); gulp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ rebuild script '(cd app && npm rebuild --runtime=electron --target=1.4.6 --disturl=https://atom.io/download/atom-shell --build-from-source); gulp build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     (cd app && npm rebuild --runtime=electron --target=1.4.6 --disturl=https://atom.io/download/atom-shell --build-from-source); gulp build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/serapath/Desktop/beaker/npm-debug.log
```

**npm-debug.log**
```
0 info it worked if it ends with ok
1 verbose cli [ '/home/serapath/.nvm/versions/node/v5.11.0/bin/node',
1 verbose cli   '/home/serapath/.nvm/versions/node/v5.11.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'rebuild' ]
2 info using npm@4.0.3
3 info using node@v5.11.0
4 verbose run-script [ 'prerebuild', 'rebuild', 'postrebuild' ]
5 info lifecycle @~prerebuild: @
6 silly lifecycle @~prerebuild: no script for prerebuild, continuing
7 info lifecycle @~rebuild: @
8 verbose lifecycle @~rebuild: unsafe-perm in lifecycle true
9 verbose lifecycle @~rebuild: PATH: /home/serapath/.nvm/versions/node/v5.11.0/lib/node_modules/npm/bin/node-gyp-bin:/home/serapath/Desktop/beaker/node_modules/.bin:/home/serapath/.nvm/versions/node/v5.11.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
10 verbose lifecycle @~rebuild: CWD: /home/serapath/Desktop/beaker
11 silly lifecycle @~rebuild: Args: [ '-c',
11 silly lifecycle   '(cd app && npm rebuild --runtime=electron --target=1.4.6 --disturl=https://atom.io/download/atom-shell --build-from-source); gulp build' ]
12 silly lifecycle @~rebuild: Returned: code: 1  signal: null
13 info lifecycle @~rebuild: Failed to exec rebuild script
14 verbose stack Error: @ rebuild: `(cd app && npm rebuild --runtime=electron --target=1.4.6 --disturl=https://atom.io/download/atom-shell --build-from-source); gulp build`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/home/serapath/.nvm/versions/node/v5.11.0/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (/home/serapath/.nvm/versions/node/v5.11.0/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid @
16 verbose cwd /home/serapath/Desktop/beaker
17 error Linux 3.19.0-32-generic
18 error argv "/home/serapath/.nvm/versions/node/v5.11.0/bin/node" "/home/serapath/.nvm/versions/node/v5.11.0/bin/npm" "run" "rebuild"
19 error node v5.11.0
20 error npm  v4.0.3
21 error code ELIFECYCLE
22 error @ rebuild: `(cd app && npm rebuild --runtime=electron --target=1.4.6 --disturl=https://atom.io/download/atom-shell --build-from-source); gulp build`
22 error Exit status 1
23 error Failed at the @ rebuild script '(cd app && npm rebuild --runtime=electron --target=1.4.6 --disturl=https://atom.io/download/atom-shell --build-from-source); gulp build'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the  package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     (cd app && npm rebuild --runtime=electron --target=1.4.6 --disturl=https://atom.io/download/atom-shell --build-from-source); gulp build
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by pfrazee** [comment]
This is something to do with an IPFS dependency. I thought I had solved it with some custom forks (node-webcrypto-ossl should not be getting installed). I suspect another IPFS dep recently added it. I'll investigate, sorry for the delay

**Comment by pfrazee** [comment]
@serapath Ok I've pushed a fix. Pull master and run `npm run burnthemall`

**Comment by serapath** [comment]
thx <3 :-)

**Comment by serapath** [comment]
oh just figured that it's `burn them all` and not `burn the mall`.

if i type `npm start` the browser starts and everything seems to work.

...still, in the terminal, it logs:
`[IPFS] Error fetching IPFS daemon version: ECONNREFUSED`

...and during the rebuild process i got:

```
  CXX(target) Release/obj.target/leveldown/src/leveldown.o
  CXX(target) Release/obj.target/leveldown/src/leveldown_async.o
  SOLINK_MODULE(target) Release/obj.target/leveldown.node
  COPY Release/leveldown.node
make: Leaving directory `/home/serapath/Desktop/beaker/app/node_modules/leveldown/build'

> sqlite3@3.1.8 install /home/serapath/Desktop/beaker/app/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

make: Entering directory `/home/serapath/Desktop/beaker/app/node_modules/sqlite3/build'
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c
  TOUCH Release/obj.target/deps/action_before_build.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3150000/sqlite3.o
  AR(target) Release/obj.target/deps/sqlite3.a
  COPY Release/sqlite3.a
  CXX(target) Release/obj.target/node_sqlite3/src/database.o
../src/database.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE node_sqlite3::Database::New(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/database.cc:133:96: warning: ‘bool v8::Object::ForceSet(v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated (declared at /home/serapath/.node-gyp/iojs-1.4.6/deps/v8/include/v8.h:2701): Use CreateDataProperty / DefineOwnProperty [-Wdeprecated-declarations]
     info.This()->ForceSet(Nan::New("filename").ToLocalChecked(), info[0].As<String>(), ReadOnly);
                                                                                                ^
../src/database.cc:134:86: warning: ‘bool v8::Object::ForceSet(v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated (declared at /home/serapath/.node-gyp/iojs-1.4.6/deps/v8/include/v8.h:2701): Use CreateDataProperty / DefineOwnProperty [-Wdeprecated-declarations]
     info.This()->ForceSet(Nan::New("mode").ToLocalChecked(), Nan::New(mode), ReadOnly);
                                                                                      ^
../src/database.cc: In static member function ‘static void node_sqlite3::Database::Work_BeginOpen(node_sqlite3::Database::Baton*)’:
../src/database.cc:144:9: warning: unused variable ‘status’ [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),
         ^
../src/database.cc: In static member function ‘static void node_sqlite3::Database::Work_BeginClose(node_sqlite3::Database::Baton*)’:
../src/database.cc:230:9: warning: unused variable ‘status’ [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),
         ^
../src/database.cc: In static member function ‘static void node_sqlite3::Database::Work_BeginExec(node_sqlite3::Database::Baton*)’:
../src/database.cc:525:9: warning: unused variable ‘status’ [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),
         ^
../src/database.cc: In static member function ‘static void node_sqlite3::Database::Work_BeginLoadExtension(node_sqlite3::Database::Baton*)’:
../src/database.cc:625:9: warning: unused variable ‘status’ [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),
         ^
  CXX(target) Release/obj.target/node_sqlite3/src/node_sqlite3.o
  CXX(target) Release/obj.target/node_sqlite3/src/statement.o
../src/statement.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE node_sqlite3::Statement::New(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/statement.cc:103:74: warning: ‘bool v8::Object::ForceSet(v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated (declared at /home/serapath/.node-gyp/iojs-1.4.6/deps/v8/include/v8.h:2701): Use CreateDataProperty / DefineOwnProperty [-Wdeprecated-declarations]
     info.This()->ForceSet(Nan::New("sql").ToLocalChecked(), sql, ReadOnly);
                                                                          ^
../src/statement.cc: In static member function ‘static void node_sqlite3::Statement::Work_BeginPrepare(node_sqlite3::Database::Baton*)’:
../src/statement.cc:118:9: warning: unused variable ‘status’ [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),
         ^
In file included from ../src/statement.cc:6:0:
../src/statement.cc: In static member function ‘static void node_sqlite3::Statement::Work_BeginBind(node_sqlite3::Statement::Baton*)’:
../src/macros.h:125:9: warning: unused variable ‘status’ [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),                              \
         ^
../src/statement.cc:322:5: note: in expansion of macro ‘STATEMENT_BEGIN’
     STATEMENT_BEGIN(Bind);
     ^
../src/statement.cc: In static member function ‘static void node_sqlite3::Statement::Work_BeginGet(node_sqlite3::Statement::Baton*)’:
../src/macros.h:125:9: warning: unused variable ‘status’ [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),                              \
         ^
../src/statement.cc:370:5: note: in expansion of macro ‘STATEMENT_BEGIN’
     STATEMENT_BEGIN(Get);
     ^
../src/statement.cc: In static member function ‘static void node_sqlite3::Statement::Work_BeginRun(node_sqlite3::Statement::Baton*)’:
../src/macros.h:125:9: warning: unused variable ‘status’ [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),                              \
         ^
../src/statement.cc:438:5: note: in expansion of macro ‘STATEMENT_BEGIN’
     STATEMENT_BEGIN(Run);
     ^
../src/statement.cc: In static member function ‘static void node_sqlite3::Statement::Work_BeginAll(node_sqlite3::Statement::Baton*)’:
../src/macros.h:125:9: warning: unused variable ‘status’ [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),                              \
         ^
../src/statement.cc:504:5: note: in expansion of macro ‘STATEMENT_BEGIN’
     STATEMENT_BEGIN(All);
     ^
../src/statement.cc: In static member function ‘static void node_sqlite3::Statement::Work_BeginEach(node_sqlite3::Statement::Baton*)’:
../src/macros.h:125:9: warning: unused variable ‘status’ [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),                              \
         ^
../src/statement.cc:601:5: note: in expansion of macro ‘STATEMENT_BEGIN’
     STATEMENT_BEGIN(Each);
     ^
../src/statement.cc: In static member function ‘static void node_sqlite3::Statement::Work_BeginReset(node_sqlite3::Statement::Baton*)’:
../src/macros.h:125:9: warning: unused variable ‘status’ [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),                              \
         ^
../src/statement.cc:724:5: note: in expansion of macro ‘STATEMENT_BEGIN’
     STATEMENT_BEGIN(Reset);
     ^
  SOLINK_MODULE(target) Release/obj.target/node_sqlite3.node
  COPY Release/node_sqlite3.node
  COPY /home/serapath/Desktop/beaker/app/node_modules/sqlite3/lib/binding/electron-v1.4-linux-x64/node_sqlite3.node
  TOUCH Release/obj.target/action_after_build.stamp
make: Leaving directory `/home/serapath/Desktop/beaker/app/node_modules/sqlite3/build'

> node-webcrypto-ossl@1.0.16 install /home/serapath/Desktop/beaker/app/node_modules/node-webcrypto-ossl
> node-gyp rebuild

make: Entering directory `/home/serapath/Desktop/beaker/app/node_modules/node-webcrypto-ossl/build'
  CXX(target) Release/obj.target/nodessl/src/main.o
In file included from ../src/node/../core/common.h:7:0,
                 from ../src/node/common.h:4,
                 from ../src/main.cpp:1:
../src/node/../core/scoped_ssl.h:6:25: fatal error: openssl/aes.h: No such file or directory
 #include <openssl/aes.h>
                         ^
compilation terminated.
make: *** [Release/obj.target/nodessl/src/main.o] Error 1
make: Leaving directory `/home/serapath/Desktop/beaker/app/node_modules/node-webcrypto-ossl/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/serapath/.nvm/versions/node/v5.11.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 3.19.0-32-generic
gyp ERR! command "/home/serapath/.nvm/versions/node/v5.11.0/bin/node" "/home/serapath/.nvm/versions/node/v5.11.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/serapath/Desktop/beaker/app/node_modules/node-webcrypto-ossl
gyp ERR! node -v v5.11.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

npm ERR! Linux 3.19.0-32-generic
npm ERR! argv "/home/serapath/.nvm/versions/node/v5.11.0/bin/node" "/home/serapath/.nvm/versions/node/v5.11.0/bin/npm" "rebuild" "--runtime=electron" "--target=1.4.6" "--disturl=https://atom.io/download/atom-shell" "--build-from-source"
npm ERR! node v5.11.0
npm ERR! npm  v4.0.3
npm ERR! code ELIFECYCLE
npm ERR! node-webcrypto-ossl@1.0.16 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-webcrypto-ossl@1.0.16 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-webcrypto-ossl package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-webcrypto-ossl
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-webcrypto-ossl
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/serapath/Desktop/beaker/app/npm-debug.log
[10:51:17] Using gulpfile ~/Desktop/beaker/gulpfile.js
[10:51:17] Starting 'bundle'...
[10:51:17] Starting 'less'...
Treating 'browser-es-module-loader/dist/babel-browser-build' as external dependency
Treating 'browser-es-module-loader/dist/browser-es-module-loader' as external dependency
Treating 'jayson/promise' as external dependency
[10:51:18] Finished 'less' after 464 ms
[10:51:19] Finished 'bundle' after 1.7 s
[10:51:19] Starting 'build'...
[10:51:19] Finished 'build' after 15 μs
```

**Comment by pfrazee** [comment]
> oh just figured that it's burn them all and not burn the mall

Hahah yep, the mad king do what he do

> ...still, in the terminal, it logs: [IPFS] Error fetching IPFS daemon version: ECONNREFUSED

Yeah that's because you're not running the IPFS daemon. If you want to use IPFS, you need to run it independently of Beaker.

> ...and during the rebuild process i got:

That's what should've been fixed by my PR. Did you get that after pulling latest and running burnthemall?
