### ISSUE TITLE
npm run watch throws Error - ubuntu

### ISSUE THREAD

**Issue by pmario** [beakerbrowser/beaker#269]
Operation System: ubuntu 16.10
Beaker Version: 0.6.0  compiled from master:latest

If I run `npm run watch` it throws an error. `[IPFS] Error fetching IPFS daemon version: ECONNREFUSED` ... That's because IPFS is not installed on the machine. ... 

**Expected behaviour:**

Since IPFS isn't a "hard dependency", it shouldn't throw an error. 

```
$$$:~/git/beaker$ npm run watch

> @ watch /home/mario/git/beaker
> gulp start-watch

[12:51:26] Using gulpfile ~/git/beaker/gulpfile.js
[12:51:26] Starting 'bundle'...
[12:51:26] Starting 'less'...
Treating 'browser-es-module-loader/dist/babel-browser-build' as external dependency
Treating 'browser-es-module-loader/dist/browser-es-module-loader' as external dependency
Treating 'jayson/promise' as external dependency
[12:51:27] Finished 'less' after 444 ms
[12:51:28] Finished 'bundle' after 1.38 s
[12:51:28] Starting 'build'...
[12:51:28] Finished 'build' after 18 μs
[12:51:28] Starting 'watch'...
[12:51:28] Finished 'watch' after 7.9 ms
[12:51:28] Starting 'start-watch'...
Spawning electron /home/mario/git/beaker/node_modules/electron/dist/electron
[12:51:28] Finished 'start-watch' after 6.98 ms
[IPFS] Error fetching IPFS daemon version: ECONNREFUSED
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: watch /home/mario/git/beaker/app/node_modules/es5-ext/string/#/contains/is-implemented.js ENOSPC
    at exports._errnoException (util.js:1022:11)
    at FSWatcher.start (fs.js:1429:19)
    at Object.fs.watch (fs.js:1456:11)
    at createFsWatchInstance (/home/mario/git/beaker/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/mario/git/beaker/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/mario/git/beaker/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/home/mario/git/beaker/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (/home/mario/git/beaker/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at FSReqWrap.oncomplete (fs.js:123:15)

npm ERR! Linux 4.8.0-34-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "watch"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @ watch: `gulp start-watch`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ watch script 'gulp start-watch'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp start-watch
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mario/git/beaker/npm-debug.log

```

**Comment by pfrazee** [comment]
Actually that exception isnt related to the IPFS error -- or, it shouldnt be, anyway.

You're getting an ENOSPC error from the file-watcher. Is it possible you have some volume that's out of space?

**Comment by pmario** [comment]
It's a new laptop 256GB SSD and only about 20GB used atm.

**Comment by pfrazee** [comment]
That error code is misleading. Google for that error + file watching. You
may need to increase a limit in the sys config

**Comment by pmario** [comment]
thx. It works now. did search for `ENOSPC file watching` as suggested and found: 
https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers which also gives some more details.
