### ISSUE TITLE
Uncaught error when cancelling creating a new site

### ISSUE THREAD

**Issue by taravancil** [beakerbrowser/beaker#451]
```
main.js:4653 Uncaught (in promise) UserDeniedError: User denied permission
    at createError (beaker://shell-window/main.js:6598:16)
    at onCbReply (beaker://shell-window/main.js:6581:17)
    at EventEmitter.onIPCMessage (beaker://shell-window/main.js:6520:14)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
```

**Comment by pfrazee** [comment]
This isn't a bug, it's just an unhandled rejection created by the user (by clicking cancel)
