### ISSUE TITLE
0.7.2 won't start on ubuntu 17.04 using node 8

### ISSUE THREAD

**Issue by pmario** [beakerbrowser/beaker#510]
Operation System: ubuntu 17.04
Beaker Version: latest master. 0.7.2 https://github.com/beakerbrowser/beaker/commit/facf6a901aa76250a319f683aba65032b3ad7006

node v8.0.0

I did a `burnthemall` and get this:

```
[mario:~/git/beaker] master(+10/-167,1054)+* 6m34s ± 
-> npm run start

> @ start /home/mario/git/beaker
> gulp start

[21:12:33] Using gulpfile ~/git/beaker/gulpfile.js
[21:12:33] Starting 'start'...
Spawning electron /home/mario/git/beaker/node_modules/electron/dist/electron
[21:12:33] Finished 'start' after 3.63 ms
App threw an error during load
Error: Cannot find module 'last-one-wins'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/home/mario/git/beaker/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/mario/git/beaker/app/node_modules/hypercore/index.js:2:11)
    at Object.<anonymous> (/home/mario/git/beaker/app/node_modules/hypercore/index.js:1073:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'last-one-wins'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/home/mario/git/beaker/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/mario/git/beaker/app/node_modules/hypercore/index.js:2:11)
    at Object.<anonymous> (/home/mario/git/beaker/app/node_modules/hypercore/index.js:1073:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
^C

```

**Comment by pfrazee** [comment]
New NPM is weird. Try running `npm install ; cd app ; npm install` and let me know if its starts then

**Comment by pmario** [comment]
strange - I get the following: 

```
[mario:~/git/beaker] master(+10/-167,1054)+* 1m37s ± 
-> npm i

> macos-alias@0.2.11 install /home/mario/git/beaker/node_modules/macos-alias
> node-gyp rebuild

make: Verzeichnis „/home/mario/git/beaker/node_modules/macos-alias/build“ wird betreten
  CXX(target) Release/obj.target/volume/src/volume.o
../src/volume.cc:9:2: error: #error This platform is not implemented yet
 #error This platform is not implemented yet
  ^~~~~
../src/volume.cc: In function ‘void Initialize(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’:
../src/volume.cc:16:49: error: ‘MethodGetVolumeName’ was not declared in this scope
     Nan::GetFunction(Nan::New<FunctionTemplate>(MethodGetVolumeName)).ToLocalChecked());
                                                 ^~~~~~~~~~~~~~~~~~~
volume.target.mk:95: die Regel für Ziel „Release/obj.target/volume/src/volume.o“ scheiterte
make: *** [Release/obj.target/volume/src/volume.o] Fehler 1
make: Verzeichnis „/home/mario/git/beaker/node_modules/macos-alias/build“ wird verlassen
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Linux 4.10.0-21-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/mario/git/beaker/node_modules/macos-alias
gyp ERR! node -v v8.0.0
gyp ERR! node-gyp -v v3.6.1
gyp ERR! not ok 

> undefined postinstall /home/mario/git/beaker
> cd app && npm install

npm WARN beaker-browser@0.7.2 No repository field.
npm WARN beaker-browser@0.7.2 No license field.

up to date in 1.691s
npm WARN beaker No repository field.
npm WARN beaker No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: macos-alias@0.2.11 (node_modules/macos-alias):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: macos-alias@0.2.11 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

added 1 package in 7.043s

[mario:~/git/beaker] master(+12/-168,1054)+* 1m47s ± 
-> cd app

[mario:~/git/beaker/app] master(+12/-168,1054)+* 2m55s ± 
-> npm i
npm WARN beaker-browser@0.7.2 No repository field.
npm WARN beaker-browser@0.7.2 No license field.

up to date in 1.619s

[mario:~/git/beaker/app] master(+12/-168,1054)+* 2m58s ± 
-> cd ..

[mario:~/git/beaker] master(+12/-168,1054)+* 3m1s ± 
-> npm start

> @ start /home/mario/git/beaker
> gulp start

[22:14:08] Using gulpfile ~/git/beaker/gulpfile.js
[22:14:08] Starting 'start'...
Spawning electron /home/mario/git/beaker/node_modules/electron/dist/electron
[22:14:08] Finished 'start' after 3.83 ms
App threw an error during load
Error: Cannot find module 'last-one-wins'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/home/mario/git/beaker/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/mario/git/beaker/app/node_modules/hypercore/index.js:2:11)
    at Object.<anonymous> (/home/mario/git/beaker/app/node_modules/hypercore/index.js:1073:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'last-one-wins'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/home/mario/git/beaker/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/mario/git/beaker/app/node_modules/hypercore/index.js:2:11)
    at Object.<anonymous> (/home/mario/git/beaker/app/node_modules/hypercore/index.js:1073:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
^C

```

**Comment by pfrazee** [comment]
Bleh, what the heck. Try these, in order, and see if any one solves it:

 - `cd app ; npm up`
 - `cd app ; rm package-lock.json ; npm i`
 - `cd app ; rm -Rf node_modules ; npm i ; cd .. ; npm run rebuild`

**Comment by pmario** [comment]
nope. no success with any of them

**Comment by pfrazee** [comment]
That's super weird. If you do `ls app/node_modules/last-one-wins`, do you see files?

**Comment by pmario** [comment]
>That's super weird. If you do ls app/node_modules/last-one-wins, do you see files?

yes. It's really strange. 

```
[mario:~/git/beaker] master(+21/-15,1054)+* 19h47m36s ± 
-> ll app/node_modules/last-one-wins/
insgesamt 48
drwxr-xr-x   2 mario mario  4096 Jun  6 22:35 ./
drwxr-xr-x 259 mario mario 12288 Jun  6 22:36 ../
-rw-r--r--   1 mario mario   385 Nov 28  2015 example.js
-rw-r--r--   1 mario mario   712 Jän 30  2016 index.js
-rw-r--r--   1 mario mario  1079 Jän  1  2015 LICENSE
-rw-r--r--   1 mario mario    13 Jän  1  2015 .npmignore
-rw-r--r--   1 mario mario  1387 Jun  6 22:35 package.json
-rw-r--r--   1 mario mario  1312 Nov 28  2015 README.md
-rw-r--r--   1 mario mario  1804 Jän 30  2016 test.js
-rw-r--r--   1 mario mario    69 Nov 28  2015 .travis.yml
```

**Comment by pfrazee** [comment]
What in tarnation.

Let's try this: first run `npm cache clean`. Then clone a fresh copy of beaker and try to install and run. If that doesn't work then we'll bring in the priest.

**Comment by pmario** [comment]
I did switch back to node v6.11.0 ... which works.  seems to be a problem with mismatching precompiled  native modules
