### ISSUE TITLE
Error while idling rotonde.

### ISSUE THREAD

**Issue by creationix** [beakerbrowser/beaker#760]
Operation System: OSX 10.13.1
Beaker Version: 0.7.8 official binary (updated automatically from previous version)

First it had two of these

```
Uncaught Exception:
RangeError: Source is too large
    at Uint8Array.set (native)
    at new WASM (/Applications/Beaker Browser.app/Contents/Resources/app.asar/node_modules/xsalsa20/index.js:46:19)
    at new XSalsa20 (/Applications/Beaker Browser.app/Contents/Resources/app.asar/node_modules/xsalsa20/index.js:17:46)
    at XSalsa20 (/Applications/Beaker Browser.app/Contents/Resources/app.asar/node_modules/xsalsa20/index.js:14:43)
    at new XOR (/Applications/Beaker Browser.app/Contents/Resources/app.asar/node_modules/sodium-javascript/crypto_stream.js:23:20)
    at Object.exports.crypto_stream_xor_instance (/Applications/Beaker Browser.app/Contents/Resources/app.asar/node_modules/sodium-javascript/crypto_stream.js:19:10)
    at Protocol.feed (/Applications/Beaker Browser.app/Contents/Resources/app.asar/node_modules/hypercore-protocol/index.js:122:34)
    at /Applications/Beaker Browser.app/Contents/Resources/app.asar/node_modules/hypercore/lib/replicate.js:23:26
    at /Applications/Beaker Browser.app/Contents/Resources/app.asar/node_modules/hypercore/index.js:132:15
    at apply (/Applications/Beaker Browser.app/Contents/Resources/app.asar/node_modules/hypercore/node_modules/thunky/index.js:44:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```
<img width="434" alt="screen shot 2017-11-16 at 11 24 38 am" src="https://user-images.githubusercontent.com/89353/32905865-d8c4a55c-cac0-11e7-9ccd-c0e5854e4210.png">

Then this:

```
Uncaught Exception:
TypeError: Cannot read property 'update' of null
    at Protocol.feed (/Applications/Beaker Browser.app/Contents/Resources/app.asar/node_modules/hypercore-protocol/index.js:133:47)
    at /Applications/Beaker Browser.app/Contents/Resources/app.asar/node_modules/hypercore/lib/replicate.js:23:26
    at /Applications/Beaker Browser.app/Contents/Resources/app.asar/node_modules/hypercore/index.js:132:15
    at apply (/Applications/Beaker Browser.app/Contents/Resources/app.asar/node_modules/hypercore/node_modules/thunky/index.js:44:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

No errors in the site's console

**Comment by creationix** [comment]
If it helps, my rotonde is dat://8992c9b73e0732400818eda247424b364527a6202d2dc7984a87bbd129f4c0bc/

**Comment by pfrazee** [comment]
@creationix we literally *just* released v0.7.9 with a fix for this. Update your beaker!

**Comment by creationix** [comment]
lol, nice

**Comment by brechtpm** [comment]
Seeing this error again on the 0.8 beta, so this might have to be reopened. I'm running a build from master, with this as the most recent commit: https://github.com/beakerbrowser/beaker/commit/d82215aa232e58fc09ad2e0813d2a71c8888390f. If needed I can try updating later.

![beaker-error-01](https://user-images.githubusercontent.com/6107054/37875399-51305862-3036-11e8-979d-572639da761f.png)

**Comment by pfrazee** [comment]
@brechtpm ok that's interesting. Thanks for filing. Can you do an `npm ls` inside the `beaker/app` directory and tell me what versions you have for `xsalsa20` and `sodium-javascript` ?

**Comment by brechtpm** [comment]
For `xsalsa20` I've got v1.0.2, and `sodium-javascript` is v0.5.5.

**Comment by pfrazee** [comment]
@brechtpm ok I'm escalating the issue to upstream.

Most people's builds dont use `sodum-javascript`, they use `sodium-native`. If you're using the JS version it's because there was a build failure.

Could you try running `npm run rebuild` in your root directory?

**Comment by pfrazee** [comment]
Then run `npm start` and see if you get this anymore.
