### ISSUE TITLE
*.AppImage does not run on CentOS Linux release 7.4.1708

### ISSUE THREAD

**Issue by Chaz6** [beakerbrowser/beaker#763]
Operation System: CentOS Linux release 7.4.1708 (Core)
Beaker Version: 0.7.9

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/.org.chromium.Chromium.twuA6u)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/tmp/.mount_beakerwHIKih/app/resources/app.asar/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Object.<anonymous> (/tmp/.mount_beakerwHIKih/app/resources/app.asar/node_modules/sqlite3/lib/sqlite3.js:190:3)
```

**Comment by pfrazee** [comment]
Thanks for reporting. Out of curiosity, do you know if you're using a 32bit or 64bit distro?

**Comment by probonopd** [comment]
This means that it was compiled on a system with a glibc version newer than what comes with CentOS Linux release 7.4.1708. It is generally recommended to compile what goes into an AppImage on the oldest system the code can be built on, in order to maximize compatibility.

As for this issue, also check https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#libstdcso6.

**Comment by Chaz6** [comment]
> 
> 
> Thanks for reporting. Out of curiosity, do you know if you're using a 32bit or 64bit distro?

I am using a 64bit distro. Thanks!
