### ISSUE TITLE
Start Error: `TypeError: siphash.ready is not a function`

### ISSUE THREAD

**Issue by composition4** [beakerbrowser/beaker#765]
```
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: siphash.ready is not a function
    at Object.<anonymous> (~/beaker/app/node_modules/sodium-javascript/crypto_shorthash.js:11:9)
    at Object.<anonymous> (~/beaker/app/node_modules/sodium-javascript/crypto_shorthash.js:19:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (~/beaker/app/node_modules/sodium-javascript/index.js:1774:9)
```

fix attempts
* burnthemall
* git hard reset
* include missing module in various areas of app

Operation System: ubu 17.10 linux-i686-4.10
Beaker Version: 0.7.9
npm: 5.5.1
nodejs: 8.9.0

**Comment by pfrazee** [comment]
This was just fixed in sodium-javascript 0.5.3 (https://github.com/sodium-friends/sodium-javascript/commits/master). Can you pull your latest npm deps, make sure you have that version, and try again?

**Comment by composition4** [comment]
It appears that I've got beaker running again. Sodium-native or js regardless I have a UI now. Thank you!

**Comment by pfrazee** [comment]
Good deal
