### ISSUE TITLE
Error dialog at startup

### ISSUE THREAD

**Issue by wesleytodd** [beakerbrowser/beaker#773]
Operation System: macOS
Beaker Version: 0.7.9

Happened when opening beaker as the start page was rendering.  It did complete rendering and seemed to work after the error dialog was closed.  It did not happen upon consecutive close/opens.

```
Uncaught Exception:
TypeError: Cannot read property '_selections' of null
    at Object.undownloadAll (/Applications/Beaker Browser.app/Contents/Resources/app.asar/background-process.build.js:3191:24)
    at Feed.archive._autodownloader.onUpdate.throttle (/Applications/Beaker Browser.app/Contents/Resources/app.asar/background-process.build.js:3195:33)
    at Feed.throttled (/Applications/Beaker Browser.app/Contents/Resources/app.asar/background-process.build.js:184:21)
    at emitThree (events.js:135:13)
    at Feed.emit (events.js:216:7)
    at Feed._writeDone (/Applications/Beaker Browser.app/Contents/Resources/app.asar/node_modules/hypercore/index.js:676:46)
    at ondone (/Applications/Beaker Browser.app/Contents/Resources/app.asar/node_modules/hypercore/index.js:667:10)
    at onwrite (/Applications/Beaker Browser.app/Contents/Resources/app.asar/node_modules/random-access-file/index.js:181:14)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:691:5)
```

**Comment by pfrazee** [comment]
Thanks for the report, just pushed a fix.
