### ISSUE TITLE
Cannot read property 'focus' of null

### ISSUE THREAD

**Issue by jaszczur** [beakerbrowser/beaker#892]
**Operating system:**
Linux 4.15.9-1-ARCH
node v9.8.0
npm 5.7.1

**This is:**
- [x] a bug
- [ ] general feedback

**Beaker version:**
Both *0.8.0 prerelease 1* from appimage and compiled-from-source git master 0c704f01

**Description**
An error is displayed during startup:

```
Uncaught Exception:
TypeError: Cannot read property 'focus' of null
    at EventEmitter.electron.ipcMain.on (/tmp/.mount_beakerCLJm1x/app/resources/app.asar/background-process.build.js:1775:47)
    at emitOne (events.js:120:20)
    at EventEmitter.emit (events.js:210:7)
    at WebContents.<anonymous> (/tmp/.mount_beakerCLJm1x/app/resources/electron.asar/browser/api/web-contents.js:266:13)
    at emitTwo (events.js:125:13)
    at WebContents.emit (events.js:213:7)
```

**Comment by pfrazee** [comment]
Thanks for filing, we'll check into it.

**Comment by pfrazee** [comment]
Handled in 3aa7415fd891cbc3ffdd4c454af2e70166695779
