### ISSUE TITLE
new test runner completely fails on ubuntu 17.10

### ISSUE THREAD

**Issue by pmario** [beakerbrowser/beaker#927]
Operation System: ubuntu 17.10
Beaker version: latest master: f3b5a726c98b4701e3bf3798e794171adf6ca769

seems to be a GTK initialization problem

```
[mario:~/git/beaker/tests] master(2535)+ 7m34s ± 
-> npm run test

> beaker-browser-test@0.0.0 test /home/mario/git/beaker/tests
> ava ./*-test.js -s

(electron:14655): Gtk-WARNING **: cannot open display: 
(electron:14664): Gtk-WARNING **: cannot open display: 
(electron:14673): Gtk-WARNING **: cannot open display: 
(electron:14682): Gtk-WARNING **: cannot open display: 
(electron:14691): Gtk-WARNING **: cannot open display: 

  5 failed

  archives-web-api-test › before

  Promise returned by test never resolved
  workspaces-test › before
  Promise returned by test never resolved
  dat-archive-web-api-test › before
  Promise returned by test never resolved
  browser-test › before
  Promise returned by test never resolved
  bookmarks-web-api-test › before
  Promise returned by test never resolved

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! beaker-browser-test@0.0.0 test: `ava ./*-test.js -s`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the beaker-browser-test@0.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mario/.npm/_logs/2018-03-28T19_21_42_401Z-debug.log

[mario:~/git/beaker/tests] master(2535)+ 7m41s 1 ± 
```

**Comment by pmario** [comment]
I did an other test: 

```
[mario:~/git/beaker/tests] master(+2/-0,2535)+* 20m11s ± 
-> ava ./apps-test-disabled.js -s
[
  "Logfile: /home/mario/.config/Beaker Browser/debug.log",
  "User data path set by environment variables",
  "userData: /tmp/beaker-test-dMsV1w",
  "[25098:0329/095152.759271:INFO:CONSOLE(169)] \"%cElectron Security Warning (Disabled webSecurity)\", source: /home/mario/git/beaker/node_modules/electron/dist/resources/electron.asar/renderer/security-warnings.js (169)"
]

  2 failed

  before

  /home/mario/git/beaker/tests/execute(<Function>, "require") - api.js:73

  Rejected promise returned by test. Reason:

  Error {
    details: undefined,
    message: `unknown error: The inAppPurchase module can only be used on macOS␊
    Error: The inAppPurchase module can only be used on macOS␊
        at Object.<anonymous> (/home/mario/git/beaker/node_modules/electron/dist/resources/electron.asar/browser/api/in-app-purchase.js:4:9)␊
        at Object.<anonymous> (/home/mario/git/beaker/node_modules/electron/dist/resources/electron.asar/browser/api/in-app-purchase.js:16:3)␊
        at Module._compile (module.js:642:30)␊
        at Object.Module._extensions..js (module.js:653:10)␊
        at Module.load (module.js:561:32)␊
        at tryModuleLoad (module.js:504:12)␊
        at Function.Module._load (module.js:496:3)␊
        at Module.require (module.js:586:17)␊
        at require (internal/module.js:11:18)␊
        at Object.get [as inAppPurchase] (/home/mario/git/beaker/node_modules/electron/dist/resources/electron.asar/browser/api/exports/electron.js:11:16)␊
        at EventEmitter.<anonymous> (/home/mario/git/beaker/node_modules/electron/dist/resources/electron.asar/browser/rpc-server.js:271:59)␊
        at emitTwo (events.js:126:13)␊
        at EventEmitter.emit (events.js:214:7)␊
        at WebContents.<anonymous> (/home/mario/git/beaker/node_modules/electron/dist/resources/electron.asar/browser/api/web-contents.js:295:13)␊
        at emitTwo (events.js:126:13)␊
        at WebContents.emit (events.js:214:7)`,
    seleniumStack: {
      message: 'An unknown server-side error occurred while processing the command.',
      orgStatusMessage: `unknown error: The inAppPurchase module can only be used on macOS␊
      Error: The inAppPurchase module can only be used on macOS␊
          at Object.<anonymous> (/home/mario/git/beaker/node_modules/electron/dist/resources/electron.asar/browser/api/in-app-purchase.js:4:9)␊
          at Object.<anonymous> (/home/mario/git/beaker/node_modules/electron/dist/resources/electron.asar/browser/api/in-app-purchase.js:16:3)␊
          at Module._compile (module.js:642:30)␊
          at Object.Module._extensions..js (module.js:653:10)␊
          at Module.load (module.js:561:32)␊
          at tryModuleLoad (module.js:504:12)␊
          at Function.Module._load (module.js:496:3)␊
          at Module.require (module.js:586:17)␊
          at require (internal/module.js:11:18)␊
          at Object.get [as inAppPurchase] (/home/mario/git/beaker/node_modules/electron/dist/resources/electron.asar/browser/api/exports/electron.js:11:16)␊
          at EventEmitter.<anonymous> (/home/mario/git/beaker/node_modules/electron/dist/resources/electron.asar/browser/rpc-server.js:271:59)␊
          at emitTwo (events.js:126:13)␊
          at EventEmitter.emit (events.js:214:7)␊
          at WebContents.<anonymous> (/home/mario/git/beaker/node_modules/electron/dist/resources/electron.asar/browser/api/web-contents.js:295:13)␊
          at emitTwo (events.js:126:13)␊
          at WebContents.emit (events.js:214:7)␊
        (Session info: content shell=)␊
        (Driver info: chromedriver=2.29 (8e8216e581c512667203931f81c1a1ead47222e5),platform=Linux 4.13.0-37-generic x86_64)`,
      type: 'UnknownError',
    },
    type: 'RuntimeError',
  }



  cleanup

  /home/mario/git/beaker/tests/node_modules/spectron/lib/application.js:59

  Rejected promise returned by test. Reason:

  Error {
    message: 'Application not running',
  }

  Application.stop (node_modules/spectron/lib/application.js:59:48)
  Test._ava2.default.after.always [as fn] (apps-test-disabled.js:37:13)


```

**Comment by pmario** [comment]
may be a problem with the mac "auto-update" .. feature

**Comment by pfrazee** [comment]
Turns out I needed to inherit the process.env in the spawned browser process. Fixed!

**Comment by pmario** [comment]
thx. works 62 passed, 2 skipped - ubuntu 17.10 ... latest master
