### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by jamesthedisciple** [beakerbrowser/beaker#946]
Operating system: Linux: MX-Linux 17.1 (debain 9)
Version 8.0 pr5 
This is:

- [x ] a bug
- [ ] general feedback

This pop up window shows on app launch:

A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Cannot read property 'focus' of null
    at EventEmitter.electron.ipcMain.on (/var/tmp/.mount_beakerpi1Xne/app/resources/app.asar/background-process.build.js:1775:47)
    at emitOne (events.js:120:20)
    at EventEmitter.emit (events.js:210:7)
    at WebContents.<anonymous> (/var/tmp/.mount_beakerpi1Xne/app/resources/electron.asar/browser/api/web-contents.js:266:13)
    at emitTwo (events.js:125:13)
    at WebContents.emit (events.js:213:7)

**Comment by pfrazee** [comment]
Thanks for filing, I'll look into it.
