### ISSUE TITLE
Unable to build in Linux

### ISSUE THREAD

**Issue by icarito** [beakerbrowser/beaker#972]
Operation System: Debian 9
Beaker version: git master

```
14151 verbose stack Error: ad-block@2.1.0 preinstall: `npm install bloom-filter-cpp && npm install hashset-cpp`
14151 verbose stack Exit status 1
14151 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
14151 verbose stack     at emitTwo (events.js:126:13)
14151 verbose stack     at EventEmitter.emit (events.js:214:7)
14151 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
14151 verbose stack     at emitTwo (events.js:126:13)
14151 verbose stack     at ChildProcess.emit (events.js:214:7)
14151 verbose stack     at maybeClose (internal/child_process.js:925:16)
14151 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14152 verbose pkgid ad-block@2.1.0
14153 verbose cwd /home/icarito/Proyectos/beaker/app
14154 verbose Linux 4.14.0-0.bpo.3-amd64
14155 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
14156 verbose node v8.9.4
14157 verbose npm  v5.6.0
14158 error code ELIFECYCLE
14159 error errno 1
14160 error ad-block@2.1.0 preinstall: `npm install bloom-filter-cpp && npm install hashset-cpp`
14160 error Exit status 1
14161 error Failed at the ad-block@2.1.0 preinstall script.
14161 error This is probably not a problem with npm. There is likely additional logging output above.
14162 verbose exit [ 1, true ]
```

**Comment by icarito** [comment]
I updated node to 8.11 and was able to build and install dependencies!

Thanks!
